### ISSUE TITLE
Publish matrix for Boosters and where each is available

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#102]
Based on metadata in the Booster Catalog, automatically publish a matrix showing each Booster and the environments in which they're made available, ie: OSO Starter, OSO Pro, OSIO, Staging, etc.

**Comment by quintesse** [comment]
Ok, that shouldn't be too hard, except that I don't know where we would publish this to? What do you have in mind @ALRubinger ?

**Comment by gastaldi** [comment]
In a Wiki page here would be a good choice: https://github.com/fabric8-launcher/launcher-documentation/wiki

**Comment by ALRubinger** [comment]
Or we could coordinate with @rhoads-zach about how to best surface this on the community site

**Comment by krishnapaparaju** [comment]
Adding an architecture diagram would help in understanding each booster...

**Comment by ALRubinger** [comment]
@krishnapaparaju Please open a separate issue describing what you'd like out of an arch diagram for each  Mission

**Comment by rhoads-zach** [comment]
What about the concept of a new "Mission Guide"

Outline:
- Intro content
  - explanation of mission approach
  - explanation of runtimes
- booster matrix
- Missions 
  - REST
    - overview
    - list of available runtimes
    - possible diagram
  - CRUD
....
- Runtimes
  - WFS
  - VX
....

@ALRubinger @gastaldi @quintesse  thoughts?

**Comment by gastaldi** [comment]
Out of date, closing
