### ISSUE TITLE
Consider switching the order of mission / runtime in catalog

### ISSUE THREAD

**Issue by metacosm** [fabric8-launcher/launcher-planning#106]
… so that the folder hierarchy would be runtime / mission / version instead of mission / runtime / version.
It would make things easier for booster maintainers to update the boosters (everything in the same parent folder vs. tracking down changes across folders).

**Comment by gastaldi** [comment]
I think that makes sense from the booster maintainer PoV (and future contributors too). 

/cc @hbraun, @cescoffier, @cmoulliard @lholmquist?

**Comment by heiko-braun** [comment]
Fine with me either way

**Comment by metacosm** [comment]
Since missions can also be runtime-specific, it makes more sense to organize things by runtime first then mission. It would also mirror discussed changes in launcher UI. Finally, I think it fits how developer think (at least, how *I* think developers think, I guess I shouldn't generalize): usually, runtime is a given (I know that's I'm using technology X) so that's what I'd like to choose first.

**Comment by quintesse** [comment]
@metacosm the reasoning behind this is that if you first choose a technology you might be missing out on all kinds of interesting missions that aren't available for your favorite technology but perhaps they use another technology that would still be acceptable to you. So from an exploratory standpoint the current order is much better. Luckily the new UI will make this issue go away and show you all options on a single page.

**Comment by lholmquist** [comment]
i think i'm good with this change,  i know for node boosters, we might have boosters that other runtimes might not have, so this would work

**Comment by gastaldi** [comment]
+1 Changing the runtime to be the root folder in booster-catalog, will let us use the Github's CODEOWNERS feature to ask for PR reviews from the codeowners of each runtime before merging

**Comment by gastaldi** [comment]
I've been discussing with @quintesse and we think that *runtimes/versions/missions* would be more adequate for runtime owners. 

Why
====
- When a new version is introduced, the runtime owner just needs to copy the folder of the current version and perform the required changes in the booster.yaml files

When
====
- @quintesse is working on this and should provide a PR to the booster-catalog along with updates in the backend

**Comment by Ladicek** [comment]
Makese sense to me.

**Comment by quintesse** [comment]
This was done a while ago already. Closing.
