### ISSUE TITLE
Add description to Runtimes

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#111]
According to the new Runtime UI, the Runtime entries require a description. It should be added to the Booster catalog.

Mockup: https://redhat.invisionapp.com/share/VGF1RF15J#/screens/279916120

@quintesse predicted that in https://github.com/fabric8-launcher/launcher-booster-catalog-service/pull/21#issuecomment-358641924

**Comment by quintesse** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-booster-catalog-service/issues/28
