### ISSUE TITLE
Jarring transition between intro screen and "wizard" screen in launcher

### ISSUE THREAD

**Issue by bmicklea** [fabric8-launcher/launcher-planning#114]
Problem:
The space creation and initial screen for the launcher are both black overlays that cover the OSIO top bar. Having gone through two screens similarly formatted the user believes that they should expect this style of screen as the configuration experience.

However, following the import or new project selection the user is dropped into a vertical "wizard" that is no longer an overlay and switches to main content on white background.

The effect is jarring and confuses the user because it seems to indicate that they're in a different part of the product and doing some other type of config (or perhaps not doing config at all?).

Possible solution:
It would be clearer to maintain consistency with:
- Overlay or non-overlay
- All black or black-nav with white-input area

**Comment by gastaldi** [comment]
I think this issue belongs to ngx-launcher?

**Comment by bmicklea** [comment]
I'm not sure @ALRubinger asked me to drop it here...

**Comment by gastaldi** [comment]
They seem to be very specific to the UI. 

Feel free to continue adding here, we can always move them to another repository later when triaging

**Comment by ALRubinger** [comment]
Yep, main triage here and we'll put it in the appropriate component repo as necessary.  Sending to Erik to figure who he'd like to have handle it and what to do. :)

**Comment by bmicklea** [comment]
If it's better to move them that's fine...I don't mind.

**Comment by edewit** [comment]
This issue was moved to fabric8-launcher/ngx-launcher#89
