### ISSUE TITLE
OSIO launcher needs different Git treatment

### ISSUE THREAD

**Issue by bmicklea** [fabric8-launcher/launcher-planning#115]
For OSIO GitHub authorization happens as part of user registration. So in the launcher the Git section doesn't need to do authorization (and shouldn't ask for it). It may be necessary to have some interaction here:
- Choose the organization
- Rename the repo (I think we can safely auto-populate with the project name as default)

It also may be interesting to explain on this page that we'll be creating a repo, adding source code for the sample project as well as kubernetes YAML files needed to define the pods. This would clarify the value of the launcher over something simplistic like start.sprint.io and help the user understand why their Git credentials might have been asked for earlier.

**Comment by ALRubinger** [comment]
Before we get to coding, let's run this through UXD to get a clear understanding of what the OSIO-specific treatment should be.  Updated screens would be really helpful and we can run 'em by @bmicklea to ensure they address the issue as intended.

**Comment by bmicklea** [comment]
Great, how quickly can that be done? I don't want to slow you down but feel these are important to close off.

**Comment by ALRubinger** [comment]
Will leave to @catrobson's team to scope out the work; they've already got some of this addressed. :)

**Comment by catrobson** [comment]
We have a few use cases for OpenShift.io:

* The user has already been authorized in OpenShift.io.  In that case, we show the account that is authorized, and allow the user to choose the organization and name for a new repo.  Design for this situation: https://redhat.invisionapp.com/share/VGF1RF15J#/275860642_Authorize_Git_Provider_-Full_Width-_-_Connected_-_Visuals
* The user has not already been authorized to Github.  In that case, the flow from a UI standpoint is the same as the Launch experience, adding github authorization and then allowing for the choice of organization and naming of the new repo.  The implementation of authorization for OpenShift.io will act differently behind the scenes, using our authorization service to store the github connection information for further use in OpenShift.io. Designs from empty state (use arrow keys to move through screens): https://redhat.invisionapp.com/share/VGF1RF15J#/275860461_Authorize_Git_Provider_-Full_Width-_-_Disconnected_-_Visuals

We have another use case for importing existing projects where we allow users to browse their existing repos in Github.  This is also captured for design and in progress for UI implementation.

It looks like the only thing we haven't done is put in a default project name based on @bmicklea's comments above.  We could easily do this based on the mission & runtime I expect.  I'll talk to the team about adding a default name in the UI layer.

Anything else I missed @ALRubinger, @bmicklea ?

**Comment by bmicklea** [comment]
@catrobson looks good to me.

**Comment by gastaldi** [comment]
@bmicklea looks like it was addressed already, can we close this issue?

**Comment by bmicklea** [comment]
Agreed, closing as fixed.
