### ISSUE TITLE
Authorization token is needed not X-git-token for git related services

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-launcher/launcher-planning#117]
Passing Authorization bearer token here but not X-git-token it gives 401

```
curl -X GET \
  https://forge.api.prod-preview.openshift.io/api/services/git/organizations \
  -H 'authorization: Bearer  token' \
  -H 'x-app: osio' \
  -H 'x-git-provider: GitHub'
```

if i won't pass Authorization bearer token here but pass X-git-token it works as in 

```
curl -X GET \
  https://forge.api.prod-preview.openshift.io/api/services/git/organizations \
  -H 'x-app: osio' \
  -H 'x-git-provider: GitHub' \
  -H 'x-git-token: token'
```

so looks like X-git-token we need to pass , Authorization bearer has no effect. As per my understanding we just need to pass Authorization Bearer not X-git-token.

**Comment by gastaldi** [comment]
@invincibleJai weird, I tried this and it works: 
```
http --form GET https://forge.api.prod-preview.openshift.io/api/services/git/repositories "Authorization:Bearer $OSIO_STAGING_TOKEN" X-App:osio --timeout 100
```

I used httpie.org

**Comment by invincibleJai** [comment]
there was issue with token , verified works fine.
