### ISSUE TITLE
Changes in the API for Missions screen based on new UX

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-launcher/launcher-planning#120]
As per the new UX (https://redhat.invisionapp.com/share/VGF1RF15J#/screens/279916120) and this related PR (https://github.com/fabric8-launcher/ngx-launcher/pull/90), 

Missions require the following extra parameters 

prerequisite: string;
suggested: boolean;
description: string;

Also, description field is missing from the existing response as well. That has to be included.

to be passed from API in order to handle layout changes.

**Comment by quintesse** [comment]
[This change](https://github.com/fabric8-launcher/launcher-booster-catalog-service/issues/30) that was just committed and will be available in the near future will allow you to add whatever attributes you like to a `metadata` section in the Missions, Runtimes and Versions in the Booster Catalog. You can then decide for yourself what properties you'd like to add and how you'd like to display them in the UI.

**Comment by arunkumars08** [comment]
@quintesse Thanks for the update 👍 Will follow up once the change is ready.

**Comment by arunkumars08** [comment]
@quintesse I see the PR for the change has been closed, is it available in prod-preview?

**Comment by arunkumars08** [comment]
@quintesse Any status on this?

**Comment by arunkumars08** [comment]
@gastaldi Could you reopen this as the changes aren't still reflected in prod-preview.
