### ISSUE TITLE
Changes in the API for Runtimes as per new UX

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-launcher/launcher-planning#121]
As per the new UX (https://redhat.invisionapp.com/share/VGF1RF15J#/screens/279916120) and this related PR (https://github.com/fabric8-launcher/ngx-launcher/pull/90), 

Runtimes require the following extra parameters 

prerequisite: string;
suggested: boolean;
description: string;

Also, description field is missing from the existing response as well. That has to be included.

to be passed from API in order to handle layout changes.

**Comment by quintesse** [comment]
[This change](https://github.com/fabric8-launcher/launcher-booster-catalog-service/issues/30) that was just committed and will be available in the near future will allow you to add whatever attributes you like to a `metadata` section in the Missions, Runtimes and Versions in the Booster Catalog. You can then decide for yourself what properties you'd like to add and how you'd like to display them in the UI.

**Comment by arunkumars08** [comment]
@quintesse Thanks for the update 👍 Will follow up once the change is ready.

**Comment by invincibleJai** [comment]
@quintesse i couldn't see changes in prod-preview , is it yet to be moved to stage? have tried here 

`curl -X GET "https://forge.api.prod-preview.openshift.io/api/booster-catalog/runtimes" -H "accept: application/json" -H "X-App: osio"`

**Comment by quintesse** [comment]
@invincibleJai no, it isn't in staging yet

**Comment by invincibleJai** [comment]
@quintesse thanks, so when do we have plan to promote it to prod-preview?? as it's needed there for us to be consumed

**Comment by edewit** [comment]
what does `prerequisite` mean in this context?

**Comment by mindreeper2420** [comment]
Prerequisite is a term UX is using to state that there are pieces the user needs to understand or know about before they should select that give option. In the case of Secured, the user should understand the basic concepts around Red Hat SSO. Think of it as a call out to signal that the user should expand the row to read more.

I believe the information would all have to come from the API as the content should match whatever the list item is. The prerequisite information for Secured most likely won't be the same for others?

**Comment by arunkumars08** [comment]
@mindreeper2420 Thanks Adam for the clarification. @edewit This is the screen where you can see the prerequisite UX - https://redhat.invisionapp.com/share/6BEZL73M7#/screens/281657307

This is also as per the new UX tagged earlier in the description of the issue.

The extra fields needed are:

1. prerequisite
2. description
3. suggested

**Comment by arunkumars08** [comment]
@quintesse Any status on this?

**Comment by gastaldi** [comment]
Merged in https://github.com/fabric8-launcher/launcher-backend/commit/5b9b2352c5f8cbbe99a1e7b389ad30386c94873a

**Comment by arunkumars08** [comment]
@gastaldi Could you reopen this as the changes aren't still reflected in prod-preview.
