### ISSUE TITLE
Changes in Pipelines API as per the new UX

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-launcher/launcher-planning#122]
Based on new UX (https://redhat.invisionapp.com/share/VGF1RF15J#/screens/275860321) and the related PR (https://github.com/fabric8-launcher/ngx-launcher/pull/90), pipeline screen shows description for all the stages

In order to address that, we need changes in the API as well to bring in this as it currently doesn’t bring description for all stages.
https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines

Pipelines screen would require the following new properties from API.
Note that instead of a pipeline description, each stage has a name and description.

```
suggested?: boolean;
 techpreview?: boolean;
 stages: [
{ 
description: string; 
name: string; 
}
];

```

Sample Response (Current)
```
[

		{
			id: "django-releaseandstage",
			platform: "django",
			name: "Release and Stage",
			description: "Django based pipeline which creates a new version then builds and deploys the project",
			stages:  [
				"Build Release",
				"Rollout to Stage"
			],
			suggested: false
		}
]
```

**Comment by gastaldi** [comment]
The problem is that we extract this information from https://github.com/fabric8io/fabric8-jenkinsfile-library and that doesn't describe the stage individually. 

@pradeepto is this something you guys could help?

**Comment by quintesse** [comment]
Also, could you explain _why_ you'd need a name and a description for each pipeline stage? AFAICT they are literally just a bunch of labels without any strict identifying purpose. Couldn't you for example generate an identifier from the description? (eg. `description.toLowerCase().replace(" ", "_")` or something like that)

**Comment by gastaldi** [comment]
@quintesse afaik that is part of the new UI. @invincibleJai showed me the updated UI was changed to include a description for each stage

**Comment by quintesse** [comment]
Aha, well in that case somebody should in touch with the maintainers of the jenkinsfile library I guess. Is that pradeepto that you mentioned?

**Comment by gastaldi** [comment]
Yes, I believe so. He is from the Build team

**Comment by arunkumars08** [comment]
@quintesse As @gastaldi mentioned, it is to address the new UX changes which currently takes description for each of the stages.

**Comment by dlabrecq** [comment]
The UXD team performed a couple usability studies with the app-launcher and the old pipeline layout did not test well. For example, the descriptions were difficult to read and each pipeline was only visible if an expandable area was opened. To correct these issues, the pipelines were moved and each stage was given its own description to help with readability.

The new pipelines layout is shown below, with separate stage descriptions. This tested well during the second usability study when the app-launcher was retested.

![screen shot 2018-03-02 at 3 49 09 pm](https://user-images.githubusercontent.com/17481322/36929448-bcb89886-1e5e-11e8-8c5e-b686b5532c3e.png)

For reference, this is the old pipelines layout, with unreadable descriptions. This did not test well during the first usability study.

![screen shot 2018-03-02 at 9 12 54 pm](https://user-images.githubusercontent.com/17481322/36929461-d27df652-1e5e-11e8-9e83-cd51b574f251.png)

FYI, the current API (represented by the old pipeline layout above) returns a string containing asterisks which appear to separate different stage descriptions. This string is also mixed with `\\n` line breaks, apparently in an attempt to format the description in the UI? Unfortunately, deserializing HTML strings is not good practice and opens a Cross-site scripting (XSS) security vulnerability.

**Comment by gastaldi** [comment]
@dlabrecq that content is markdown extracted from the README files inside each pipeline in https://github.com/fabric8io/fabric8-jenkinsfile-library. Can this be rendered somehow by the UI? I think it would be a little difficult to get the formatting out of the descriptions and even if we do that, rendering in the UI may not provide the desired output

Example: https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/maven/ReleaseStageApproveAndPromote/ReadMe.md

**Comment by gastaldi** [comment]
Or we can talk to the Build team who is responsible of maintaining that repository to add the necessary information

**Comment by dlabrecq** [comment]
Thank you for the links. Unfortunately, the content of the ReadMe.md above isn't really what the UI needs to show to the user. That particular markdown describes the ReleaseStageApproveAndPromote pipeline overall; however, usability testing shows that the UI needs to better describing each stage, individually to the user. 

Wherever the content comes from, it should also not be provided as markdown. Ideally, the descriptions would just be ASCII strings.

**Comment by gastaldi** [comment]
@pradeepto ping us in the Fabric8-launcher channel in MM. Let's talk about how we can enhance the repository to include this information

**Comment by GeorgeActon** [comment]
@gastaldi if we cannot get this from the jenkinsfile library, what other alternatives do we have?

**Comment by gastaldi** [comment]
@GeorgeActon we're talking with the Build team about ownership of that repository. We're still planning on changing the files in that repository.

**Comment by GeorgeActon** [comment]
@gastaldi Do you have any commit on when this can b done yet?

**Comment by maxandersen** [comment]
Just make a PR. We’ll get it reviewed and pushed if works :)

**Comment by gastaldi** [comment]
@animuk the idea is to change the metadata.yaml files inside https://github.com/fabric8io/fabric8-jenkinsfile-library to contain this new information. 

For example, https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/maven/ReleaseStageApproveAndPromote/metadata.yml would be like:

```yaml
suggested: true
tech-preview: false
environments:
  - Test
  - Stage
  - Run
stages:
  - name: Build Release
    description: creates a new version then builds and deploys the project into the maven repository
  - name : xxxx
    description: yyyy
    ...
```

Bear in mind that once this change is pushed to master, it will break [the legacy addon](https://github.com/fabric8-launcher/launcher-backend/tree/master/addons/legacy-osio-addon/src/main/java/io/fabric8/forge/generator/pipeline) and [the new endpoint](https://github.com/fabric8-launcher/launcher-backend/tree/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins), so make sure to provide PRs for them too

**Comment by gastaldi** [comment]
@animuk can we count on you to have this ready by March 16th?

**Comment by gastaldi** [comment]
@GeorgeActon the API changes are now in staging. @animuk is working now in getting the description values correct, but that shouldn't block any work.

**Comment by invincibleJai** [comment]
Thanks @gastaldi @animuk
