### ISSUE TITLE
Show error messages in ngx-launcher

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#125]
I had one question here. In the progress screen which is the last screen for getting-started flow, i don't see any placeholders for error messages to show in the html file. We need to show the error messages if we get from the /osio/launch call right ? And these error messages are sent to the UI, through the web socket call.

And this is the progress message page, i am talking about
https://github.com/fabric8-launcher/ngx-launcher/blob/master/src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html

**Comment by GeorgeActon** [comment]
@catrobson I think dan was raising this to you for design input. can you comment /give ETA on when this can be addressed.

**Comment by catrobson** [comment]
@GeorgeActon @jyasveer we actually need some engineering input to update the designs properly to reflect the different type of error messages, we're not sure what gets returned at this point.  @gastaldi was helping on the RHOAR/Launcher mailing list.  

@bdellasc is working on this right now, so any input you can provide would help us get the information out faster for designs.

**Comment by GeorgeActon** [comment]
@catrobson George would be the person who have the knowledge. What mailing list is that? I dont see any comments fromGeorge on this topic on the Google group topic "Setup Progress Screen Scenarios"

**Comment by gastaldi** [comment]
>George would be the person who have the knowledge

Am I? This is a UI issue afaik, and I think the UXD team is the best resource for this

**Comment by GeorgeActon** [comment]
@gastaldi I think the question was what different types of error messages would be returned. Is that correct @catrobson ?

**Comment by gastaldi** [comment]
@GeorgeActon ah your statement was a bit ambiguous :smiley: 

The errors are modeled in https://app.swaggerhub.com/apis/fabric8-launcher/backend/2.0.0 but basically it returns:
- 400 when validation fails
- 401 if authentication/authorization fails
- 500 when an internal error occurs

**Comment by catrobson** [comment]
Are there errors that can happen for each "step" of the application build-out - sort of like we had before here:  https://redhat.invisionapp.com/share/7SCC7SN5E#/screens/231315304?  Is it these same 3 errors that can be returned overall or for those steps?  (basically how much detail can we give the user about what went wrong and where)

**Comment by gastaldi** [comment]
@catrobson the backend has some specific endpoints to validate if a Github repository or an Openshift repository exists, so I'd say that besides that, validation in the backend only happens when the Finish button is clicked. In the frontend I think validation should happen locally (like check if a required input was provided, etc)

**Comment by catrobson** [comment]
@gastaldi I think I asked my question the wrong way.  I'm not asking about validating the input from the Launch Experience.  I'm asking about once we hit the finish button - things start actually happening.

So, 
- A the booster gets added into github (in OpenShift, OpenShift.io use cases)
- An OpenShift project gets created
- A pipeline gets added to that project
etc...

If during the process of executing those actions, something goes wrong, can we provide detailed feedback to the user about what went wrong, and how they can recover from it?  (Delete this project in github and try again?  something else?)

**Comment by bdellasc** [comment]
Based on earlier concepts, I assume we still want to encourage the user to stay on this screen as this entire process runs?

It makes it a lot simpler to design at this point, otherwise we're going to need to address the cases when they have navigated away from this page and there are failures. My plan right now is to keep it simple and **not** give them easy ways to leave the UI until the process is done? Any links to repositories or documentation would open new browser tabs.

**Comment by Essjaysee** [comment]
If one of the 5 parts fails, and the user decides to abandon the entire launcher experience, could this leave them with (incomplete) stuff that we've added to their GitHub repository?  Is there anything else we should let them know about to clean up if setup fails and/or they abandon?

**Comment by gastaldi** [comment]
@Essjaysee yes (to the first question), if the user clicked the `Finish` button before leaving. For 2) I think it could point to documentation on what to do. Optimistically speaking, I believe the rate of failing launches will be minimal though

**Comment by bdellasc** [comment]
There are a couple of open questions:
from @catrobson: 
- "my main question is whether we need a page that shows a more generic “something went wrong, we’re not sure what” message or not."
- "I sort of doubt we always have knowledge of what step caused the issue as I bet things are happening simultaneously.  Not sure if this would have a retry button or not."  

Assuming we need specific and generic error treatments, I've posted a first pass at the error states for a few different scenarios:
- 1. Individual task-level error
  - w/specific error and has error info
  - w/generic error and no error info
- 2. General process-level w/generic error, no error info (2 options)
  - Opt A - Error state is integrated into the process header row
  - Opt B - Error state is an inline message above the list

Here is the link to the [InVision screens](https://redhat.invisionapp.com/share/CZG6Y14WEPQ)

Comments welcome and please let us know if any of these scenarios aren't needed and we can archive them.

**Comment by GeorgeActon** [comment]
@slemeur please take a look at the envision screens
@bdellasc this looks like it is focussed on the OpenShift use case. 
Ay impact on the openshift.io (OSIO) use case?

**Comment by bdellasc** [comment]
I should have probably clarified that I was looking for feedback on the general approach to how we're showing the progress through the tasks (the various states of completion), the retry option for the specific and generic errors, layout, etc. The copy still needs some work as well. 

My impression was that since the .io case is a subset of these tasks, we'd just show the appropriate tasks for .io, treated the same way (like what we do with the sections in the launcher itself). Unless this process is completely different for .io?

Once I know the layout works for folks, I could to an alternate showing the .io case (would only be a screen or two to show the difference in the task list)?

**Comment by jyasveer** [comment]
I am blocked because of this issue.
Could someone let me know where are we on this ? Because what i see is if we don't decide on the UXD and the UI implementation, I will be blocked on the integration side of tasks for the summary and status screens

**Comment by bdellasc** [comment]
I'm also blocked on finalizing the design because I've only had one comment so far on the [InVision mockups](https://redhat.invisionapp.com/share/CZG6Y14WEPQ) since Wednesday. I realize a lot of key people are in many meetings this week, but if I can get more input, I can iterate (if necessary) and then get it nailed down so @jyasveer can run with it. Thanks!

**Comment by GeorgeActon** [comment]
@catrobson Can we expedite this so we can get the design finalized by Wednesday? 

@gastaldi Can you add Stevan Lemeur to this repo so that he can be referrenced and comment directly on these issues?

**Comment by gastaldi** [comment]
@GeorgeActon I think anyone can comment and be referenced in the issues in Launcher-planning, without the need to be added? @slemeur

**Comment by GeorgeActon** [comment]
@gastaldi when I reference @slemeur he does not pop up on the list so my assumption is that he is not being alerted by the reference.

**Comment by bdellasc** [comment]
I've posted a new version of the design based on @slemeur 's comments. 
[InVision Mockups](https://redhat.invisionapp.com/share/CZG6Y14WEPQ#/285115401_Table_Of_Contents)

 There is still work being done on the text content [here](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing)

**Comment by bdellasc** [comment]
I consolidated all of the various Launcher-related InVision flows [into one place](https://redhat.invisionapp.com/share/VGF1RF15J) and updated them accordingly.

- There’s a Table of Contents in the InVision as well, to help break it down a bit.
- I’ve updated as much content that is currently finalized through @stacymcauliffe ’s work [here](https://docs.google.com/document/d/1j_178u8LptiGoxGe8xYtEzYsntVQ_wjqNLPjVJTXtcM/edit)
- I’ll be offline (Friday 22 March), but feel free to let me know if you have any questions or problems

**RHD LAUNCHER SETUP SCENARIOS**

[HAPPY PATH](https://redhat.invisionapp.com/share/VGF1RF15J#/286891656_OSO_-)_Next_Steps_-Happy_Path-_)

[SAD PATH](https://redhat.invisionapp.com/share/VGF1RF15J#/286893670_Alt_Screen_Title_-_Next_Steps_OSO_-Sad_Path-/)

[CANCEL](https://redhat.invisionapp.com/share/VGF1RF15J#/286894428_Alt_Screen_Title_-_OSO_-_Cancel_Set_Up_-RHD_Launch-)

**RHD LAUNCHER & OSIO SETUP SCENARIOS**

[NAVIGATE AWAY FROM WHILE PROCESSES ARE STILL RUNNING](https://redhat.invisionapp.com/share/VGF1RF15J#/286903695_Alt_Screen_Title_-_OSO_-_Navigate_Away_From_Set_Up)

**OSIO SETUP SCENARIOS**

[BASIC LAYOUT](https://redhat.invisionapp.com/share/VGF1RF15J#/286895165_Title_-_Set_Up_New_Application_-OSIO-)

[OSIO CANCEL SETUP
](https://redhat.invisionapp.com/share/VGF1RF15J#/286895160_Alt_Screen_Title_-_OSIO_-_Cancel_Set_Up)

**ZIP SETUP SCENARIOS**

[BASIC LAYOUT
](https://redhat.invisionapp.com/share/VGF1RF15J#/286892654_Title_-_RHD_Launch_-_Select_Target_Env_-ZIP-_4)

**Comment by edewit** [comment]
@bdellasc very nice added some comments to the InVision document

**Comment by gastaldi** [comment]
Out of date, closing
