### ISSUE TITLE
/osio/launch - gitOrganization parameter issue

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#131]
In `/osio/launch` api with this request below
```
curl -X POST \
  https://forge.api.prod-preview.openshift.io/api/osio/launch \
  -H 'authorization: Bearer <stage-token>' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'x-app: osio' \
  -H 'x-execution-step-index: 0' \
  -H 'x-git-provider: GitHub' \
  -d 'missionId=crud&runtimeId=vert.x&runtimeVersion=redhat&pipelineId=maven-release&projectName=app-test-17&projectVersion=124.554&groupId=124-644&artifactId=d4.345&spacePath=/myspace&gitOrganization=fabric8-analytics&gitRepository=a-new-repository-20'
```
#### Scenario 1
I pass the `gitOrganization` value as `fabric8-analytics` and i get the error as below :-
```
{"id":"edbb20e8-5e95-4f7c-a0e4-376278dd4566","data":{"error":"repository not found 'fabric8-analytics/a-new-repository-20'"},"statusMessage":null}
```
#### Scenario 2
I dont pass the `gitOrganization` value in the request data. And i get this error :-
```
{"id":"905e599e-7741-4669-aac2-ce7b83fb6686","data":{"error":"User does not belong to organization '' or the organization does not exist"},"statusMessage":null}
```
#### Scenario 3
I pass `gitOrganization` as `jyasveer` which is my gitHub user space. And yet i am getting a error like below:
```
{"id":"1f105169-dded-4fa6-9585-106ac89397e1","data":{"error":"User does not belong to organization 'jyasveer' or the organization does not exist"},"statusMessage":null}
```
#### Scenario 4
I do not pass the `gitOrganization` key at all in the request payload. And this is the error i see
```
[
    {
        "message": "java.lang.NullPointerException: gitOrganization"
    }
]
```

I want to understand out of the above 4 scenarios, at least one case should allow me to create a git repo. Is there something i am doing here ?

As per my understanding, even if i dont have any organization under my git namespace, this api should allow me to create a repo under my namespace which is not happening now. Please correct me here if i am wrong ?

**Comment by jyasveer** [comment]
thats true @invincibleJai

**Comment by gastaldi** [comment]
@ia3andy can you have a look? I think it may be related with the changes introduced in 7a66d7b709bc68621e572b40c85a6b33b919fa04?

**Comment by ia3andy** [comment]
@gastaldi ok ;)

**Comment by ia3andy** [comment]
I will make a PR so that when GitOrganization is Null or empty, it will use the logged user as owner.

**Comment by ia3andy** [comment]
I found another place where there is an NPE for the gitOrganization.
I am on it and I will only push when the IT will be created to be able to test it:
https://github.com/fabric8-launcher/launcher-backend/issues/186

**Comment by gastaldi** [comment]
@jyasveer can you check again if the error persists? I've pushed a fix to this issue

**Comment by gastaldi** [comment]
@jyasveer I haven't received any feedback and it passed on my tests, so I'm closing this issue. Feel free to reopen if the problem persists

**Comment by jyasveer** [comment]
This is working now. @gastaldi :-)
