### ISSUE TITLE
name field not used when displaying versions on the Project Info page

### ISSUE THREAD

**Issue by rdruss** [fabric8-launcher/launcher-planning#133]
When you look https://github.com/fabric8-launcher/launcher-booster-catalog/blob/v20/metadata.yaml you can see:

![image](https://user-images.githubusercontent.com/367748/37487085-13100de4-2856-11e8-8b1e-5ffb946322df.png)

which implies that for the redhat (directory) version, what should be displayed is "3.4.2.redhat-009 (RHOAR".  What you actually see in the production launch service is:

![image](https://user-images.githubusercontent.com/367748/37487150-4cd81cd8-2856-11e8-8acc-827bb1712c9c.png)

**Comment by quintesse** [comment]
The fix has been merged and should be on staging shortly.
