### ISSUE TITLE
STAGE - /oiso/import - Internal 500 error

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#135]
Here is the request below i tried in Postman :-

```
curl -X POST \
  https://forge.api.prod-preview.openshift.io/api/osio/import \
  -H 'authorization: Bearer <stage-token>' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'x-app: osio' \
  -H 'x-git-provider: GitHub' \
  -b 'gitOrganization=test-organization-jyasveer&gitRepository=new-repo-13&pipelineId=maven-release&spacePath=/myspace'
```
I am getting a `Internal Error 500` error response.

**Comment by jyasveer** [comment]
@animuk @gastaldi can you please take a look ?

**Comment by gastaldi** [comment]
I'll ask the team to have a look at it. I see the following in the logs:
```
Caused by: java.lang.NullPointerException: gitRepositoryName
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.fabric8.launcher.osio.projectiles.ImmutableOsioImportProjectile$Builder.gitRepositoryName(ImmutableOsioImportProjectile.java:484)
	at io.fabric8.launcher.osio.OsioEndpoint.importRepository(OsioEndpoint.java:84)
```

**Comment by gastaldi** [comment]
@jyasveer there is a `projectName` parameter missing in the request. It was missing in the Swagger doc (or somehow lost between edits), but we have added it back. Can you try again with that parameter?

**Comment by jyasveer** [comment]
@gastaldi @edewit 
I updated the payload something like below
```
gitOrganization=test-organization-jyasveer&gitRepository=new-repo-13&pipelineId=maven-release&spacePath=/myspace&projectName=my-project
```

and i get the status code as `204 No Content`

**Comment by gastaldi** [comment]
RIght, the request should have succeeded now. It returns 204 because the method is `void`. I'll change that to return 200

**Comment by gastaldi** [comment]
@jyasveer can you try again now?

**Comment by jyasveer** [comment]
@gastaldi i get 200 now. However if i am not wrong i should get the status uuid as the response, which i am not seeing it right now.

**Comment by gastaldi** [comment]
@jyasveer we updated the Swagger doc, you shouldn't use the websocket in this call. 
I asked @edewit about that and he said: 
>well it's done within a second

**Comment by jyasveer** [comment]
@gastaldi i think work is pending here. I should get the `uuid` link from the response of /osio/import call. WDYT ?

**Comment by gastaldi** [comment]
Yes, as I told you in MM I have already implemented that and it is available in prod-preview

**Comment by jyasveer** [comment]
@gastaldi with this body data
```
gitOrganization=test-organization-jyasveer&gitRepository=new-repo-13&pipelineId=maven-release&spacePath=/testspacemarch20&projectName=my-project&spaceId=58925edc-98fd-4844-bf2e-da323473d9a2
```
i get `404 Not Found` as the response. Here i am passing the spaceId in the request body.
Any idea ?

**Comment by jyasveer** [comment]
Now I get `401` in this end point in **STAGE**
@gastaldi @animuk

**Comment by gastaldi** [comment]
@jyasveer See if you are passing the right parameters. I did this and it works: 
```
http -v --form POST https://forge.api.prod-preview.openshift.io/api/osio/import "Authorization:Bearer $OSIO_STAGING_TOKEN" X-App:osio gitRepository=fuse2 pipelineId=maven-release spaceId=$OSIO_STAGING_SPACE projectName=foo --timeout 100
```
