### ISSUE TITLE
Filter unsupported Runtimes/Missions for OSIO 

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-launcher/launcher-planning#136]
- Need to filter out Runtimes, which are not supported for OSIO like Node, Fuse
- Need to filter out Missions, which are not supported for OSIO like secured, crud, circuit-breaker

**Comment by invincibleJai** [comment]
@gastaldi @animuk FYI

**Comment by gastaldi** [comment]
@invincibleJai we can introduce a `runsOn` query parameter in the `/api/booster-catalog/missions` and `/api/booster-catalog/runtimes` endpoints, which when queried in OSIO will need to pass `runsOn=osio`.

Will that work for you?

**Comment by invincibleJai** [comment]
@gastaldi that would but that won't be needed as for these API we already pass header as in `X-App: osio` this should help to identify request is for OSIO right?

**Comment by gastaldi** [comment]
@invincibleJai I thought about that too, but `X-App` is used in another context. Let me think a bit about this

**Comment by invincibleJai** [comment]
Sure, let us know whatever works :)

**Comment by gastaldi** [comment]
@invincibleJai I thought about it and I am prefer to introduce the `runsOn` query parameter. That may be used in other use cases too (even in the standalone launcher)

**Comment by invincibleJai** [comment]
Sure @gastaldi, Sounds good !! 
thanks :)
