### ISSUE TITLE
Suggested flag shouldn't be there for all pipelines

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-launcher/launcher-planning#137]
In pipelines response https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines we get suggested: true for all pipelines. I don't think it'll make sense to show all pipelines as suggested. I believe suggested should be shown based on user-selected Runtime/Mission.That is, considering we're working from a dynamic list of mission & runtime choices.

**Comment by invincibleJai** [comment]
@animuk @ravasa Pls take a look

**Comment by gastaldi** [comment]
This issue was moved to fabric8io/fabric8-jenkinsfile-library#29
