### ISSUE TITLE
/osio/import - PROD - Do not see pipelines getting triggered in Pipelines page in OSIO

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#139]
Below is the request for the osio/import end point in prod
https://gist.github.com/jyasveer/df596df6f75a6825a064537014da3e15#file-osio-import-request

Here is the response 
```
{"uuid":"df541c56-c590-4360-a0b6-c59953628452","uuid_link":"/status/df541c56-c590-4360-a0b6-c59953628452"}
```

FYI :- I am running the setup in my local environment sourcing `PROD` environment

I do not see pipelines getting started in the Create/Pipelines page in OSIO. Below is the screenshot for the issue

<img width="1440" alt="screen shot 2018-03-23 at 1 53 10 pm" src="https://user-images.githubusercontent.com/5430080/37818862-9da1ed0a-2ea1-11e8-8995-87989661de73.png">

**Comment by jyasveer** [comment]
@gastaldi @animuk can you please look into this ?

**Comment by gastaldi** [comment]
Does in work in prod-preview?

**Comment by invincibleJai** [comment]
@edewit similar behaviour is observed for `/osio/launch` for quickstarts flow.

**Comment by edewit** [comment]
@invincibleJai yes they both use the same method to create the build config #226 fix works for both
