### ISSUE TITLE
/osio/import - PROD - Do not see codebases getting listed in Codebases page in OSIO

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#140]
Below is the request for the osio/import end point in prod
https://gist.github.com/jyasveer/df596df6f75a6825a064537014da3e15#file-osio-import-request

Here is the response 
```
{"uuid":"df541c56-c590-4360-a0b6-c59953628452","uuid_link":"/status/df541c56-c590-4360-a0b6-c59953628452"}
```

FYI :- I am running the setup in my local environment sourcing `PROD` environment

I do not see codebases getting listed in `Create/Codebases` page in OSIO. 
Below is the screenshot for the issue

<img width="1440" alt="screen shot 2018-03-23 at 1 58 15 pm" src="https://user-images.githubusercontent.com/5430080/37819068-46647016-2ea2-11e8-94c8-a496fef6b440.png">

**Comment by jyasveer** [comment]
@gastaldi @animuk can you please look into this ?

**Comment by edewit** [comment]
@jyasveer adding the generated source to the codebases used to be something that the UI did:

https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/forge-wizard/abstract-wizard.component.ts#L79-L87

**Comment by gastaldi** [comment]
@edewit yes, I moved that code to the backend. See https://github.com/fabric8-launcher/launcher-backend/issues/209

**Comment by gastaldi** [comment]
@jyasveer before update prod, can you confirm it works in prod-preview?
