### ISSUE TITLE
Enable "live filtering" of missions/runtimes

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-planning#143]
It would be very useful to have the ability to pass a parameter to the URL of the wizard that would limit the possible options in the mission and/or runtime lists.

A possible use-case would be for a runtime team, eg "Vert.x", to put a link to the launcher on a webpage of theirs or in their docs or in a quickstart guide. In that case they are only interested in showing _their_ runtime to their users.

Suggested implementation would be to add optional parameters to the URL, eg: `?mission=http-crud` or `?runtime=vert.x,wildfly,springboot`.

This could even be extended with a more flexible form of filtering that uses the info in a booster's `metadata` section. Eg. `?filter=suggested` would filter those booster that have `suggested: true` in their metadata section.

**Comment by gastaldi** [comment]
It would even use a _JSON path format_-like when declaring the flexible form of filtering: 
eg `?metadata.suggested=true`, `?metadata.istio`, and so on

**Comment by quintesse** [comment]
@gastaldi wdyt about this :point_up: as a first step to improve the current endpoints before adding GraphQL support?

You can now do stuff like: http://localhost:8080/api/booster-catalog/missions?filter=booster.runsOn("osio") which would be the same as http://localhost:8080/api/booster-catalog/missions?runsOn=osio (it's a bit mor ecomplex but also much more flexible of course)

**Comment by gastaldi** [comment]
@quintesse what's the benefit of using this strategy instead of passing each parameter individually? If it's a JavaScript expression it may lead to security issues (like `http://localhost:8080/api/booster-catalog/missions?filter=exit()` for example)

**Comment by gastaldi** [comment]
I tried something like https://stackoverflow.com/questions/20793089/secure-nashorn-js-execution, but It didn't work for me. The `BOOSTER_CATALOG_FILTER` parameter is still vulnerable to this (but at least it's only set by the administrator) :wink:

**Comment by quintesse** [comment]
What do you think about the latest version @gastaldi ?

The only thing that still needs to be fixed is that the `runsOn` parameter conflicts with this new system (both will try to use the parameter and one will fail always resulting in a `false` result). But I first wanted to run this by you to see if you agree with this approach.

**Comment by gastaldi** [comment]
@quintesse so the UI would need to call `/missions?metadata.runsOn=xx` instead of `/missions?runsOn=xx`?

**Comment by gastaldi** [comment]
Maybe for this specific case we can remove `runsOn` from the list of query parameters in the endpoint and parse the rest

**Comment by gastaldi** [comment]
But the change seems really trivial in the UI, so I'd lean towards that instead

**Comment by quintesse** [comment]
> Maybe for this specific case we can remove runsOn from the list of query parameters in the endpoint and parse the rest,

Yeah, problem is that the maps are immutable, so'd we'd first need to make a deep copy before changing it.  SOmething I'd rather avoid if I can help it.

> so the UI would need to call /missions?metadata.runsOn=xx instead of /missions?runsOn=xx?

Unfortunately `runsOn` is not a simple string comparison, but more a set.contains() with support for negation.

So if possible I'd like to support it, but we'd need to come up with a special syntax or something. Perhaps something like: `/missions?metadata.runsOn=[starter]`, where using `[ ]` would trigger a special test using the `checkNegatableCategory()` function.

**Comment by gastaldi** [comment]
@quintesse Does the requester need to know that the parameter is a set? That looks weird at a first glance. I'd expect something like `/missions?metadata.runsOn=starter` and then the implementation would take care of dealing with collections and simple strings

**Comment by quintesse** [comment]
Remember this is a _generic_ predicate, we shouldn't go hard-coding the fact that `runsOn` is a set.
