### ISSUE TITLE
Seeing ERR_CERT_COMMON_NAME_INVALID for /runtimes intermittently

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-launcher/launcher-planning#146]
Seeing ERR_CERT_COMMON_NAME_INVALID for /runtimes intermittently. It's not frequent but I observed it.

<img width="1679" alt="screen shot 2018-04-02 at 11 20 07 am" src="https://user-images.githubusercontent.com/5129024/38184850-27d1dddc-3668-11e8-96f5-8fabc85b9d1a.png">

**Comment by invincibleJai** [comment]
@animuk @gastaldi ^^

**Comment by gastaldi** [comment]
It looks like an infrastructure issue? @kbsingh any idea?

**Comment by gastaldi** [comment]
Seems to be being tracked in https://github.com/openshiftio/openshift.io/issues/2755 already. Closing
