### ISSUE TITLE
Update the description for Runtimes

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#147]
Currently we get some description for runtimes which is too long. As per discussion with @mindreeper2420 and @bdellasc in this issue https://github.com/fabric8-launcher/ngx-launcher/issues/118, description for runtimes has to be updated in the backend.

@animuk @gastaldi

**Comment by gastaldi** [comment]
@rhoads-zach can you have a look at this? Thank you!

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-booster-catalog/commit/48adb3225c4babea341ca5391c8854a56ab1c559

**Comment by jyasveer** [comment]
@gastaldi @animuk 
As per the document [https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit#](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit#) in page **5** and **6** the descriptions are mentioned.
And i don't see these descriptions in prod-preview and prod. 
Can you please verify this ?

**Comment by gastaldi** [comment]
@jyasveer the description contents in the booster catalog are the same as used in the documentation, what is wrong with the current descriptions?

**Comment by animuk** [comment]
@gastaldi  the descriptions for the runtimes and missions in the document are shorter compared to the description shown in the UI.

**Comment by gastaldi** [comment]
@rhoads-zach do you agree with the descriptions in the document? I'm fine if @rhoads-zach agrees

**Comment by rhoads-zach** [comment]
@gastaldi @animuk do you just want me to replicate the content from the linked doc? or do you want me to leave the content from my PR?

**Comment by gastaldi** [comment]
@rhoads-zach I think the idea is to use the content from the linked doc instead

**Comment by rhoads-zach** [comment]
@gastaldi no problem, i'll file a follow up PR.

**Comment by rhoads-zach** [comment]
@gastaldi @jyasveer @animuk see linked PR.

**Comment by jyasveer** [comment]
Thanks @rhoads-zach
