### ISSUE TITLE
Opening a websocket to query the launch status may use a different replica instead

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#148]
It has been observed in production that when more than 1 replica exists for the backend, it may occur that the new websocket connection is bound to the replica that doesn't have the state that triggered the launch, therefore returning no data to the requester.

It would be nicer to have SSE instead and perform the server updates in a single request, without requiring the requester to open a new Websocket connection, thus preventing the beforementioned case

**Comment by gastaldi** [comment]
OpenShift supports sticky sessions, by adding the `haproxy.router.openshift.io/balance=source` annotation to the route.

Documentation: https://docs.openshift.com/container-platform/3.7/architecture/networking/routes.html#routes-sticky-sessions

**Comment by quintesse** [comment]
It does seem to suggest though that it can't be 100% guaranteed.

**Comment by quintesse** [comment]
I'd just keep it as simple as possible. KISS. Using sticky sessions, with SSEs if we like, will probably be enough in 99% of the cases. I'd just create a nice fallback in the frontend in case it can't (re)connect to get progress.

We could either simply assume everything has completed correctly, or do a simple in-page check for the projects in GitHub and OpenShift. If they exist things probably worked.

Creating a much more complex system is not really worth it IMO.

**Comment by gastaldi** [comment]
I think we could keep the websocket approach, since SSE doesn't run on POST request

**Comment by gastaldi** [comment]
The annotation was applied in production, closing this for now.

**Comment by gastaldi** [comment]
Route annotation didn't work as expected. Reopening issue

**Comment by gastaldi** [comment]
Introduced support for JMS when multiple replicas are needed. Closing it
