### ISSUE TITLE
Support aborting a launch

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#149]
It should be possible to abort a launch after the Launch button is pressed (in the status screen) and before the flow ends

<img width="1440" alt="screen shot 2018-04-03 at 11 02 14 pm" src="https://user-images.githubusercontent.com/5430080/38265368-4b6eb162-3793-11e8-9249-21b8359cf621.png">

**Comment by quintesse** [comment]
And what would it do? Just stop or roll back?

**Comment by gastaldi** [comment]
Closing as I haven't met a real use case for this feature yet
