### ISSUE TITLE
Get `View Missions Documentation` link in the web socket response to show in the progress screen

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/launcher-planning#150]
Please find below the screenshot where i need to shoe the `View Missions Documentation` link in the progress screen.
<img width="1440" alt="screen shot 2018-04-03 at 11 02 14 pm" src="https://user-images.githubusercontent.com/5430080/38265368-4b6eb162-3793-11e8-9249-21b8359cf621.png">

**Comment by gastaldi** [comment]
Out of date, closing
