### ISSUE TITLE
change permissions of github app

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-planning#151]
We now ask full access of a users github repository including: "Full control of private repositories" we don't need delete rights and don't need access to private repos. It might scare people how much rights we want, we should limit it to what we need

**Comment by gastaldi** [comment]
I'll update the scopes in the rh-developers-launch realm from `repo,admin:repo_hook` to `admin:repo_hook,read:org,public_repo`

**Comment by gastaldi** [comment]
Changed scopes in the `rh-developers-launch`. Closing now.

**Comment by Ladicek** [comment]
I think we document the set of permissions Launcher needs from GitHub for the purpose of installing Launcher locally: https://appdev.openshift.io/docs/minishift-installation.html#creating-a-github-personal-access-token I guess this documentation should also be changed? CC @rhoads-zach

**Comment by gastaldi** [comment]
@Ladicek good call, I completely forgot that. The documentation needs to be updated, yes

**Comment by Ladicek** [comment]
Gonna file a RHOARDOC, thanks.

**Comment by rhoads-zach** [comment]
thank you @Ladicek i'll take a look
