### ISSUE TITLE
Rename OpenShift Online to OpenShift cluster or simply Openshift

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-planning#155]
When the `launcher` is running within `minishift` or `oc cluster up` that should be great to show `OpenShift cluster` or simply `Openshift` name instead of of `OpenShift online`

![screenshot 2018-04-10 20 30 21](https://user-images.githubusercontent.com/463790/38576403-4e8b3f9e-3cfe-11e8-81ef-297c9093d050.png)

**Comment by gastaldi** [comment]
@cmoulliard this UI is deprecated and replaced with https://launch.prod-preview.openshift.io/launch/new-wizard. 

Unless this is required for Summit, we're not making any changes in it.

**Comment by cmoulliard** [comment]
For local deployment of the launcher, this is not logic to use as display name `openshift online`. That will confuse the end users in this case. 

@gastaldi @ALRubinger Can you have a look on that as istio + launcher demos will then show the following screen ...

![screenshot 2018-04-19 10 04 47](https://user-images.githubusercontent.com/463790/38978955-2fac5484-43b9-11e8-925d-09c3b9958ba0.png)

**Comment by gastaldi** [comment]
@cescoffier mentioned
>there is still a Online ref in my launcher (that works very well BTW). On the very last screen, once I click on the ‘do the magic’ button

@edewit I believe he is referring to the screenshot that @cmoulliard posted in the first comment, how do we fix that?

**Comment by edewit** [comment]
@gastaldi this comes from the backend created https://github.com/fabric8-launcher/launcher-backend/pull/369 to remove it
