### ISSUE TITLE
RFC: Should Versions be the 3rd level of the booster catalog again?

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-planning#157]
So not so long ago we changed the booster catalog format from "Missions - Runtimes - Versions" to "Runtimes - Versions - Missions".

The idea to have "Runtimes" as the first level was a good one. Each runtime team can now manager their own "back yard" and add new "Missions" if and when they want.

But the decision to put "Versions" second might not have been so fortuitous. The reasoning was that:

 - All the Boosters in a "Runtime" will tend to have the same "Versions"
 - Creating a new "Version" is really easy: copy, paste & rename the folder

The thing is that we had begun to conflate "Booster Versions" with "Runtime Versions", thinking that the only reason we had "Booster Versions" was to be able to give the user the option to select between the different "Runtime Versions".

But that was never the original idea, which was to be able to have _any_ kind of way of selecting between different boosters. A "Blue" and a "Red" version for example. Or for something more practical, imagine if there's a booster with a frontend UI, one written in Angular and one written in React, then it should be possible to have an "Angular" and a "React" version.

The idea was that if you needed different types of versions you could combine them. For example you want a "Community" version and a "Redhat" version, but you _also_ want an "Angular" and a "React" version then you'd simply use the cross product and write a single list of combined versions: "Community - Angular", "Community - React", "Redhat - Angular" and "Redhat - React". (The list of options was always supposed to be short, no need to overload the user)

But in the current catalog format that would mean that _all_ boosters (in the same runtime) would have "Blue" and "Red" versions, or "Angular" and "React" ones. Or even the full list of "Community - Angular", "Community - React", "Redhat - Angular" and "Redhat - React". That's very limiting and too strict.

So the suggestion is to move "Version" back again to the 3rd level of the catalog: "Runtimes - Missions - Versions".

**Comment by gastaldi** [comment]
Not an issue once we migrate boosters to launcher-creator-backend. Closing
