### ISSUE TITLE
Standalone launcher may not scale because of GitHub's abuse rate limit

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#158]
The backend offers `/services/git/organizations`, `/services/git/repositories` and `/services/git/user` to query Github in the UI. 

It has been observed that the continuous invocation of these services may lead to instability issues due to Gateway timeouts - caused by Abuse rate limit. This may have been partially resolved with https://github.com/fabric8-launcher/launcher-backend/commit/84039e280d059c83c6b65d0731d96abe64241c86, but ideally the UI should not hit the backend to query for the Github information, as the requests will originate from different IPs.

https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

Related: https://github.com/openshiftio/openshift.io/issues/3367

## Action Items: 

- [ ] Change launcher-frontend to query GitHub directly with the token 
- [ ] Introduce a `/git/identity` in launcher-backend  to return the GitHub token (should be authenticated)
- [ ] Deprecate (and in a later step) remove `/services/git/organizations`, `/services/git/repositories` and `/services/git/user`

**Comment by ALRubinger** [comment]
I think the requests are bound to the user token, not to our service.  So each user gets their own quota.

**Comment by quintesse** [comment]
Pretty sure @ALRubinger is right here.  I'm also pretty sure that the rate limiting observed in openshiftio/openshift.io#3367 is due to the fact that they obviously don't use 500 different GH users.

**Comment by gastaldi** [comment]
We can close this issue, as connections are no longer held if the abuse limit is reached: https://github.com/fabric8-launcher/launcher-backend/commit/84039e280d059c83c6b65d0731d96abe64241c86
