### ISSUE TITLE
Launchpad on Minishift not loading on macOS with Safari

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launcher/launcher-planning#16]
When running launchpad on minishift (using either virtual box or xhyve) on macOS, I cannot use safari to load the launchpad. It prompts to accept 2 certificates, which i accept, and then goes to the error page:
<img width="823" alt="screen shot 2017-04-25 at 1 12 23 pm" src="https://cloud.githubusercontent.com/assets/208104/25400803/561db268-29b9-11e7-9bb5-07bd53702d2f.png">

Running curl gives the following:

```
$ curl -v https://192.168.99.100:8443
* Rebuilt URL to: https://192.168.99.100:8443/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to 192.168.99.100 (192.168.99.100) port 8443 (#0)
* WARNING: using IP address, SNI is being disabled by the OS.
* SSL certificate problem: Invalid certificate chain
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by rhoads-zach** [comment]
@ALRubinger @gastaldi

**Comment by rhoads-zach** [comment]
this does work if i use another browser, but still fails when trying to use ultrahook re #15

**Comment by rhoads-zach** [comment]
FYI @ALRubinger @gastaldi added a warning here until this is resolved:
https://github.com/openshiftio/appdev-documentation/pull/208

**Comment by rhoads-zach** [comment]
Once this is resolved, this warning needs to be updated:

https://github.com/openshiftio/appdev-planning/issues/16

**Comment by jorgemoralespou** [comment]
There's a known issue in origin/openshift UI with safari and self signed certs.

https://github.com/openshift/origin/issues/13506

**Comment by gastaldi** [comment]
Ultrahook is no longer used or mentioned in the docs. Closing now.
