### ISSUE TITLE
Clean frontend/ngx-launcher urls management

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-planning#162]
Since the frontend has changed a lot, url management became a bit messy.
- It takes a `http` url to make `ws` url then use it again to make it `http`
- It takes old `launchpad` url to build the new api `url`

It requires a cleaning pass.

**Comment by ia3andy** [comment]
This will be easier to accomplish when we get rid of the old wizard.

**Comment by edewit** [comment]
@ia3andy we just got rid of the old wizard ;)

**Comment by ia3andy** [comment]
I will work on that just after the catalog one :)
