### ISSUE TITLE
the .zip file is always called booster.zip, but the Launcher UI tells me to "unzip <my booster name>.zip"

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-planning#168]

**Comment by Ladicek** [comment]
Looking at the documentation, what's probably wrong is the name of the .zip file; I believe it really is supposed to be called `<my booster name>.zip`.

**Comment by gastaldi** [comment]
Duplicate of https://github.com/fabric8-launcher/launcher-frontend/issues/593

**Comment by ALRubinger** [comment]
Let's name the ZIP file to be what is shown in the UI.
