### ISSUE TITLE
Cannot Select OpenShift Cluster

### ISSUE THREAD

**Issue by sherl0cks** [fabric8-launcher/launcher-planning#169]
Looks like we have the option to select an openshift cluster now (hooray! excited use this on customer clusters). However; the UI currently deployed to https://developers.redhat.com/launch/ gets stuck when I choose the deploy to openshift option. See screenshot

![screenshot from 2018-07-03 12-32-04](https://user-images.githubusercontent.com/1335137/42240230-dd3bc202-7ec3-11e8-80ad-4b98f0ad04fc.png)

**Comment by gastaldi** [comment]
I've checked your account and I see you haven't authorized your clusters in https://sso.openshift.io/auth/realms/rh-developers-launch/account/identity. 

Make sure you have a valid OpenShift cluster allocated for you in manage.openshift.com  (we have an issue for more clarification in the UI when this happens: https://github.com/fabric8-launcher/launcher-frontend/issues/498)

**Comment by sherl0cks** [comment]
I just went an authorized one, and it works. Comments in the other issue.

I was hoping this would be an entry point to add abritatry openshift clusters, but it looks like we are stuck with just online. Really, really hoping for the day I can link up arbitrary clusters =(

**Comment by gastaldi** [comment]
The developers.redhat.com/launch launcher works with the dev.rh.com Keycloak.

You can use any clusters if you install the standalone launcher in your own environment though. Instructions in https://launcher.fabric8.io/docs/minishift-installation.html#install-launcher-app

**Comment by sherl0cks** [comment]
Roger that. Been on my list for a long time, just haven't gotten there yet.
