### ISSUE TITLE
Add a Messaging booster that allows integrating with EnMasse

### ISSUE THREAD

**Issue by david-martin** [fabric8-launcher/launcher-planning#174]
Currently the messaging booster comes with its own broker.
It would be nice if there was an option to *only* deploy the messaging booster bits that connect into a broker i.e. the frontend webapp/server parts.

We've been using a fork of the booster here https://github.com/integr8ly/nodejs-messaging-work-queue/tree/deploy_frontend_only which removes the broker (There are some other changes too for it to integrate with the crud booster via fuse)

**Comment by gastaldi** [comment]
@david-martin I think this would be better tracked as a RHOAR issue: https://issues.jboss.org/projects/RHOAR/issues. 

Closing now
