### ISSUE TITLE
Booster zip files incorrectly named

### ISSUE THREAD

**Issue by MelissaFlinn** [fabric8-launcher/launcher-planning#175]
On the  https://developers.redhat.com/launch site, when I create a booster project and click the **Set Up Application** button, the zip file for the booster project is always named booster.zip (no matter which booster I use or what project name I provided). 

![openingboosterzipdialog](https://user-images.githubusercontent.com/31925014/44866020-fbb3e780-ac51-11e8-8431-34446d7bcf4e.png)

However, the **Next Step** page of the site indicates that the zip file name is the same as the project name (which would be better if only it was true).

![nextstepspage](https://user-images.githubusercontent.com/31925014/44866039-0c645d80-ac52-11e8-95f3-021486e62090.png)

So there is a discrepancy. It is also a problem to always use booster.zip because, if I create more than one booster project, the new one overwrites the previously downloaded one.

**Comment by quintesse** [comment]
Dup of #168. Closing.
