### ISSUE TITLE
Launch - Replace Spring Boot logo with "Spring Boot" text.

### ISSUE THREAD

**Issue by jclingan** [fabric8-launcher/launcher-planning#181]
On https://developers.redhat.com/launch/, please replace occurrences of the spring boot logo with "Spring Boot" text.

**Comment by gastaldi** [comment]
> Erm, can you make the font a bit larger, probably bold, on the top-level page and a bit more on-par with the other runtimes?  No rush, but for the next push it would be nice. Thanks.
<sub>[View in Slack](https://obsidian-toaster.slack.com/archives/C33ABAG6T/p1539733473000100)</sub>
