### ISSUE TITLE
Link on Welcome App to OpenShift Console is incorrect

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#182]
I'm seeing a link to the console like `https://192.168.42.150:8443`, which is broken as it redirects to `127.0.01` on my machine.  Using a form that appends `console` to the end like `https://192.168.42.150:8443/console` appears to work nicely.

Likely this needs to be set by the backend and passed as the JSON to the welcome app?

**Comment by quintesse** [comment]
This should now work.
Btw, this assumes that the console can always be reached by appending `/console` to the end of the URL used to connect to the cluster.
