### ISSUE TITLE
Capabilities are gone from Welcome App

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#184]
![screenshot11](https://user-images.githubusercontent.com/199891/49674904-7fdfed00-fa41-11e8-84d6-376c34331ce1.png)

HTTP API?  Relational Persistence?

Tried for both Node and Boot, then assumed it was for all runtimes.

**Comment by quintesse** [comment]
Where did you test this Andrew? I just created a project on our [Pro cluster](https://console.pro-us-east-1.openshift.com/console) using [Staging](https://launch.prod-preview.openshift.io) and this is what I got:

![image](https://user-images.githubusercontent.com/778793/49675539-6b6a1780-fa76-11e8-84bf-700969f44582.png)

I used frontend + backend (verx and all capabilities)

**Comment by ALRubinger** [comment]
Thanks, @quintesse .  I was running this on Minishift using whatever versions the template `latest` images brought in.  Refreshed my Launcher and the issue disappeared, so likely some unlucky combination of versions.  Closing.

**Comment by quintesse** [comment]
Might also have been because I was still fixing a slew of bugs. Well hopefully it stays fixed ;-)
