### ISSUE TITLE
Update the Git author used to commit

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#185]
Currently we're exposing in the Git log:

`Author:	openshiftio-launchpad <obsidian-leadership@redhat.com>`

Let's talk about what this should be.  I'm thinking:

`Author: Red Hat Developers`...and as for the email address - I'm not sure yet.

**Comment by gastaldi** [comment]
We already have the `redhat-developers-launcher` GitHub user, so it's a
matter of choosing a nice email for it ;)

Em Sex, 7 de dez de 2018 21:01, Andrew Lee Rubinger <
notifications@github.com escreveu:

**Comment by ALRubinger** [comment]
I think this is now fixed: Git author comes across as @redhat-developers-launcher
