### ISSUE TITLE
Selecting "Angular" gives you "React" 

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#187]
What, are you trying to push some agenda here? :laughing: 

Repro:

1) Create an application with Angular/Boot/MySQL
2) Let it build
3) Visit the frontend route or look at the logs
4) Oh, gee, that's React! 

To satisfy the MVP, if this is quick, sure, fix it up and give us Angular.  If it's a longer fix, let's just temporarily remove Angular as an option and go with React or None.

**Comment by quintesse** [comment]
Was already fixed :-)

https://github.com/fabric8-launcher/launcher-creator-backend/commit/2b3fa02b739da94b7fe479bba4a735eb28ae916e

**Comment by ALRubinger** [comment]
Thank you!!
