### ISSUE TITLE
Application cannot be created

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#188]
Steps to repro:

1) Launcher in Staging Environment
2) Angular
3) Thorntail
4) MySQL

See:

![screenshot4](https://user-images.githubusercontent.com/199891/49767295-eebd8000-fca5-11e8-908a-a86d9bf99c4f.png)

**Comment by ALRubinger** [comment]
Same configuration but using React instead of Angular works

**Comment by gastaldi** [comment]
The error above was fixed using a hard-refresh. Closing it
