### ISSUE TITLE
Support vue.js as a Frontend option

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#192]
Requested by @tqvarnst.

@tqvarnst, mind adding some context here strengthening the argument to invest in the work to do this?  Popularity or common use case?

There are N frameworks where N = (coefficient of at least 4)*(number of days a year) and we should choose which are the most important by some reasonable analysis.  Ranking alongside Meteor, Ember, etc.

**Comment by gastaldi** [comment]
Added Vue.js support in https://github.com/fabric8-launcher/launcher-creator-backend/commit/57ea8f8da6e550f7e587f6ff79983997b6895f67, closing
