### ISSUE TITLE
Support Import from Git Flow

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#198]
In this flow, the user would enter the Git repository (and organization it belongs to), and the Openshift cluster to deploy it (if more than one cluster is available).

**Comment by ALRubinger** [comment]
To coordinate with @sbose78 :)

**Comment by ALRubinger** [comment]
Part of this issue is to draft up what we mean by "import" flows and design the various inputs, what metadata we need to assign to them (either entered by the user or inferred from the codebase) and what actions we should take with them.

**Comment by gastaldi** [comment]
It seems we could aggregate the "Deploy from ..." features (as requested in #199 and #200) into a single flow (eg. `Deploy from an existing source`) and then provide options on where to grab that source (A Git repo, Docker image, a URL to a binary build, the Maven coordinates to the binary build, etc)

**Comment by ALRubinger** [comment]
Yes, and coordinating the impl of this with teams that have similar, like FMP, ODO, etc.  Let's centralize the logic for this, and use this issue for tracking surfacing in the Launcher.

**Comment by sbose78** [comment]
Hi ! In short, this is what the import flow will do:

- Import user from Git
- Figure out what is the build type ( needed to associate a builder image )
- Choose external service ( DB, etc).
- Service binding: Find out how to map existing env vars with the external service (DB)
- Deploy

**Comment by ALRubinger** [comment]
That strikes me as one possible flow. :)

I think more realistically we should arrive at a decision tree which guides
a user from their desired input(s) to a predictable output.

We have some existing user flows for the Launcher I could see extending to
account for this case.  Would recommend we start with the smallest piece,
say importing a codebase and choosing a base image.

From there we can augment the metadata to include features like
autodetect/suggest the base image.

And then even further is the notion of binding services.  That one gets
complex as it would involve potential code changes to ensure the codebase
connects up to desired services.

So I'd like to see us first devise the decision tree, and clearly delineate
which features comprise the minimum viable deliverable for import.  Then we
may build incrementally off that.

**Comment by gastaldi** [comment]
>We have some existing user flows for the Launcher I could see extending to
account for this case.  Would recommend we start with the smallest piece,
say importing a codebase and choosing a base image.

+1, we should implement this feature as a minimum viable product first and later extend it once we have binding services implemented for other flows as well.

**Comment by redhat-developers-launcher** [comment]
I think the Git Provider input screen in this case would need to be extended or supplemented to not just include the user and organization, but allow selection of the target repo, yes?

**Comment by ALRubinger** [comment]
I think the Git Provider input screen in this case would need to be extended or supplemented to not just include the user and organization, but allow selection of the target repo, yes?

**Comment by gastaldi** [comment]
Of course, my bad, I thought Git Provider Input screen would show the target repo, updating it

**Comment by gastaldi** [comment]
Updated version

![launcher workflow from developers redhat com_launch](https://user-images.githubusercontent.com/54133/51557322-bcd23880-1e63-11e9-8ff2-f202763ba72f.png)

**Comment by ALRubinger** [comment]
And I don't mean to be difficult, but "target repo" probably doesn't need to be its own screen.  It's aggregate data that relates to the provider/org selection.  I only intended to call out that the existing Git screen we have would need to accommodate that.  

Is there a link to the editable version of this here?

**Comment by gastaldi** [comment]
Yes, the editable link is https://www.draw.io/?state=%7B%22ids%22:%5B%221um1UmCkcw8rh2s1OTHva5Cs0ZRB2qGjI%22%5D,%22action%22:%22open%22,%22userId%22:%22103593136923537342692%22%7D#G1um1UmCkcw8rh2s1OTHva5Cs0ZRB2qGjI

**Comment by gastaldi** [comment]
Updated version

![launcher workflow from developers redhat com_launch 1](https://user-images.githubusercontent.com/54133/51558310-47b43280-1e66-11e9-9d4b-c11a940bf71a.png)

**Comment by sbose78** [comment]
Looks good to me @gastaldi from a launch.openshift.io perspective. From an 'in-cluster' perspective, the first step isn't relevant since the target cluster/namespace is the 'current namespace'

**Comment by gastaldi** [comment]
@sbose78 yes, that's correct. In this case that screen won't show up since there is only one available cluster

**Comment by gastaldi** [comment]
@sbose78 do you have any thoughts on how can we find the available builder image names for a cluster?

**Comment by sbose78** [comment]
@gastaldi We have to find a way to get specific versions of builder images into the cluster registry ( or something that's allowed ) and have our code look for those specifically.
