### ISSUE TITLE
Make Git account association stateless

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#204]
This helps a more corporate archetype of a user.

At the moment Git association is done as part of Launcher installation, or relegated to an SSO instance.  Instead, we can make these parameters optional.

When in the launch flow and deploying to an OpenShift cluster, if no git credentials are found, we can present the user with an option to Authenticate with a series of Git Providers: GitHub, GitLab, Gogs, etc (whatever backends we have support for).  And once they go through those OAuth hoops, they'll be presented with the user/org/repo selection screen we already have.  All on that same "Git selection" card.

Now instead of carrying Git account state in the application scope or tied to the user identity, it's up to the user to provide it in the conversation scope while requesting a launch action.

Initially proposed by @tqvarnst.

**Comment by gastaldi** [comment]
In practical terms it means to send the Git provider Authorization info (token or encoded username/password) in the header. That's something we had initially implemented in the launcher-backend but dropped support after some time (I don't remember the exact reason), but we'll be happy to revisit that.

**Comment by ALRubinger** [comment]
Yep plus the OAuth flow which does the back-n-forthy things with GitHub to
authenticate.  And the frontend stuff to match.

**Comment by gastaldi** [comment]
The main problem with this approach is that OAuth authentication requires a fixed URL as the callback URL and considering that Launcher can be installed anywhere, I don't see how would that work without having KeyCloak or another mechanism to store tokens

**Comment by quintesse** [comment]
We should consider this an admin problem. We just have to make sure that we document clearly how people should configure their service oath callback urls.

**Comment by gastaldi** [comment]
Done
