### ISSUE TITLE
Make OpenShift account association stateless

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#205]
Can we relegate user auth to the OpenShift API?

In this arrangement we'd continue to have Launcher configured at install with a base URL.  But the user would authenticate through an OAuth web flow with the OpenShift Console instead of the Launcher getting the information directly from SSO or installation config properties.

If this is done, we'd have out-of-the-box multitenant support without any heavy config needed by the user at install time.  User management would be delegated to OpenShift.

**Comment by ALRubinger** [comment]
Requested by @tqvarnst.

**Comment by gastaldi** [comment]
We already support user impersonation in the OpenShift service in Launcher. If the user that's sent in the `Authorization` header is a valid OpenShift user, that works out-of-the-box

**Comment by gastaldi** [comment]
@edewit can we make the frontend authenticate against the openshift cluster that's installed?

**Comment by ALRubinger** [comment]
s/installed/configured to be pointed to

>

**Comment by edewit** [comment]
@gastaldi when openshift uses keycloak as well all we have to do is set the url and realm

**Comment by redhat-developers-launcher** [comment]
@edewit This scenario would relieve us from the Keycloak installation requirement and delegate auth to the configured OpenShift instance.

**Comment by ALRubinger** [comment]
This scenario would relieve us from the Keycloak installation requirement and delegate auth to the configured OpenShift instance.

**Comment by ALRubinger** [comment]
Related: #173

**Comment by gastaldi** [comment]
Done
