### ISSUE TITLE
Improve warning about enabling launch.openshift.io access to GH and OSO

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launcher/launcher-planning#21]
It wasn't overly clear that I had to take an extra step when following the link. I just ensure that my account was shown.  I can see how users will overlook this.

**Comment by SlavoKrupa** [comment]
Also if user skip this step they are stuck on  "Waiting" when deploying to OpenShift  (no error/warning...)

**Comment by Ladicek** [comment]
There could possibly be an automated validation in the Wizard for this, no>?

**Comment by liborfuka** [comment]
+1
See also https://issues.jboss.org/browse/OBST-232

**Comment by gastaldi** [comment]
A new screen was introduced in the UI allowing to bind the clusters the user has access without having to browse to Keycloak. Closing
