### ISSUE TITLE
Support multiple runtime versions in the Create flow

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#210]
The .NET team has raised this specifically as the release cadence there is frequent, and there are both community and LTS concerns.  Similarly, we've punted on this for MIddleware runtimes; it may be preferable for us to offer both community and product versions in the Create flow, granting the user choice.

This issue is to track Launcher supporting multiple versions in the create flow; it does not mandate that each runtime will have multiple versions implemented.  For that we can make new issues to build out adding new version support.

**Comment by quintesse** [comment]
This is mostly a frontend design issue, the backend has been made with versions in mind from the beginning. I'd imagine this taking no more than 2 weeks (generous estimate).

**Comment by tmds** [comment]
Was this implemented?

CC @omajid

**Comment by gastaldi** [comment]
@tmds yes, it was available for a long time, just needed to be displayed in the frontend, which is implemented now

**Comment by tmds** [comment]
Cool. Please let us know when there is an example we could use to implement support for multiple .NET Core versions.

**Comment by gastaldi** [comment]
There is an example where @quintesse implemented support for the productized Vert.x runtime: https://github.com/fabric8-launcher/launcher-creator-backend/commit/0856966cb4b09d40406b5ddee3329c591754b44d

**Comment by quintesse** [comment]
@tmds that Vert.x support George points to is perhaps a bit too specific for Maven-based projects. But basically it's very simple: in the `props` a generator gets passed there's a `runtime` property with a `name` and a `version`. You can use that version to for example copy a different set of files or make changes to certain files, etc.

If you want you can just ping me when you want to start working on this and we can discuss how to handle things for your particular situation.

**Comment by tmds** [comment]
.NET Core 3.0 is planned for September. We can look at adding that when we've released it.
