### ISSUE TITLE
Association with OSO Cluster is Broken

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#216]
I went into the SSO instance at `rh-developers-launch` and manually removed the federated identity tying my RHD account to an OpenShift Online Cluster.

Then saw in the Launcher the dialog as expected:

![screenshot15](https://user-images.githubusercontent.com/199891/54663858-06807d80-4ab9-11e9-8d29-b210a40f62b9.png)

When then attempting to configure using the provided button, got:

![screenshot16](https://user-images.githubusercontent.com/199891/54663883-19934d80-4ab9-11e9-9b9e-db66629d4e19.png)

JS Console:

```
Failed to load resource: the server forge.api.prod-preview.openshift.io/api/services/openshift/clusters:1  responded with a status of 401 (Unauthorized)
```

**Comment by gastaldi** [comment]
I cannot reproduce that, I wonder if the recent changes in the launcher-frontend fixed this?

**Comment by ALRubinger** [comment]
Indeed it has (or something has).  YES.
