### ISSUE TITLE
Selecting OpenShift Deployment can hang

### ISSUE THREAD

**Issue by rdruss** [fabric8-launcher/launcher-planning#223]
I was having trouble with selecting an "OpenShift Deployment" environment to deploy to.  When I would press the button, the application would hang without any warnings/messages.  I then went into the Federated Identity feature of Manage Account and removed, then re-added my OpenShift Pro account.  Everything started working afterwards.  Fortunately, I had the understanding to do this, but I believe it would be non-intuitive for typical users.  It would be good to be able to identify the issue that creates this problem and either autofix it or at least provide an good message to the user so they can fix it themselves.

**Comment by gastaldi** [comment]
I am facing the same issue. I have an environment configured with Keycloak and without the openshift-v3 Identity Provider set
![Screenshot from 2019-04-16 19-05-16](https://user-images.githubusercontent.com/54133/56247510-64ce5b00-607b-11e9-9dcd-716743141a35.png)

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-frontend/commit/de9ced31e6ea0529dd9061ce51d7cd5f4ec2d649, closing
