### ISSUE TITLE
Error launching Quarkus

### ISSUE THREAD

**Issue by paulrobinson** [fabric8-launcher/launcher-planning#225]
I installed Launcher into a local minishift and got an error when deploying Quarkus via the launcher. 

Versions:

* Kubernetes Master: v1.11.0+d4cacc0
* OpenShift Web Console: v3.11.0+ea42280

I installed Launcher via ```curl -s https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/master/scripts/minishift/install.sh | bash``` today.

I started a new project with:

* Frontend: Angular
* Backend: Quarkus
** Relational Persistence: enabled
** HTTP API: enabled

After hitting 'Launch", I went into the OpenShift console and watched the build happen.

The backend failed with this error log: https://pastebin.com/FeUrTM2H

**Comment by paulrobinson** [comment]
Thanks.

It seemed to only work after I removed the ```launcher``` project in OpenShift and recreated it with ```curl -s https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/master/scripts/minishift/install.sh | bash```.

Is that right?

**Comment by gastaldi** [comment]
Yes, that is correct. Another solution was to update the `launcher-creator-backend` service to use `latest`. Closing now.
