### ISSUE TITLE
Warning on Deployment Type page needs to be environment-aware

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#25]
![screenshot10](https://cloud.githubusercontent.com/assets/199891/25548037/88e76c6c-2c38-11e7-8752-f96f37d87295.png)

At the moment we always show a warning to associate federated identities to osio-launch-prod; this should be stage in the stage environment and not shown at all in Minishift environments where SSO realms are not being used at all.

**Comment by ALRubinger** [comment]
Not required and can be removed entirely if we fix #26

**Comment by gastaldi** [comment]
Out of date, closing
