### ISSUE TITLE
Do not require user to set federated identity

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#26]
We should automate the flow, if possible, such that when a user logs in, we redirect them automatically through the flow to associate federated identities for OSO and GitHub

**Comment by gastaldi** [comment]
We need to change how the authentication is handled in the frontend, but the basic is redirect the user to https:/api.openshift.io/login/authorize?link=true&redirect=https://some.endpoint.on.your.side and eventually it should come back to redirect?token=xxx

**Comment by gastaldi** [comment]
Already implemented. Closing
