### ISSUE TITLE
Error in syncing pod on first install of launch.openshift.io on Minishift/CDK

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#29]
`Error syncing pod, skipping: failed to "StartContainer" for "launchpad-frontend" with ImagePullBackOff: "Back-off pulling image \"openshiftio/launchpad-frontend:v4\""`

I typically see this when the user installs the template and the pod does not start in the allotted 600s (10m) time.  Usually because the first start attempt includes download time for the images, and if you're on a slower connection, you're gonna be sunk.

For us:

Solutions we could look at:
1) Can we tell OpenShift to bump the 600s limit?
2) Can we submit a feature request to OpenShift to bump the limit?
3) Can we submit a feature request to have k8s not include the download time as part of the start time?
4) Can we make a distro of Minishift/CDK that has launch.openshift.io template preinstalled into the Catalog and has the images bundled?

**Comment by rdruss** [comment]
Option 4 is interesting as it would just be ready after installation, but it comes with any baggage of the installation process.

What about options 0 - as you mention in your email, document this known issue for now so the user at least understands what is happening.  However, if you're on a slow enough connection will this ever work as I assume each restart starts from the beginning.  In this case, maybe explore option 5 - User configurable timeout with the default staying at 600s.

**Comment by Ladicek** [comment]
We already kinda sorta mention this in the documentation:

> Starting Minishift may trigger a download of large virtual machines or Linux container images. This may take a while.

Obviously, we could do a better job there.

In general, I think OpenShift does a fairly good job with error messages. That is, once I see them -- sometimes, the only way to get to the error message is through the _Monitoring_ tab of the OpenShift console.

In case of this error message, my instinct would be to pull the Docker image manually and retry. That's super-easy and fairly intuitive with `oc cluster`, as it reuses the Docker daemon I already have, there's no VM. It would be somewhat less intuitive with Minishift, but doable (`minishift ssh`).

If there's an option to increase the limit, that would of course be better.

**Comment by gastaldi** [comment]
Out of date. Closing
