### ISSUE TITLE
Feature: Start from blank template

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#31]
User selects dependencies and gets a blank template. 

IMO, this is really the Health Check Booster but positioned as the lowest common denominator "manual" flow, not as a Mission, and a blank starting point for the user to add/select dependencies on their own.

Everything we recommend to get started with a runtime, no extra code.

Every line in these templates would be something documentable, and can be used as a starting point to build upon all future missions

Perhaps we even implement it as a blank mission

**Comment by rdruss** [comment]
I don't think this completely captures the need.  How are needed dependencies chosen (e.g. for Swarm you would like to have MDB and CDI support or for Vert.x how are the modules to be included selected)?

**Comment by rdruss** [comment]
@cmoulliard has another interesting point:

"Generating a project/runtime should be as simple as issuing one request or selecting the fields on start.spring.io

if now, we should use LOSIO or OSIO, then the user must be first authenticated, must have access to openshift (free, paid) before to select the runtime in order to generate a project.

Is it this longer workflow that we want to ... instead of creating a project in one step using a static site start.openshift.io that we could also query using curl or forge ?"

**Comment by cmoulliard** [comment]
A good compromise could be, without the need to add another workflow to what we have on "launch.openshift.io", to provide a blank template as new mission [1] and when the user chooses it then the next screen will help him/her to select the dependencies/modules that forge will use to populate the final pom file for the zip or git project. What do you think about this idea ? If we do that, we could easily populate an openshift project as you can do with start.spring.io, wildfly-swarm.io/generator, ...

[1] Vert.x, Swarm & Vert.x mission containing a POM + BOM and dependencies selected

**Comment by rdruss** [comment]
@gastaldi, do we still have the original screens from Alpha2 that allowed you to select dependencies?  I don't recall exactly how that screen go populated as well, was it a static yaml file?

**Comment by gastaldi** [comment]
@rdruss that was provided by the Forge addons. We had a dependency on the WFSwarm, vertx and Boot addons which would render that dependency selection screen.

**Comment by cmoulliard** [comment]
So we could without too much effort reuse previous code and propose a blank mission containing for Spring Boot

```
pom.xml (Spring Boot Web starter + dependencies selected by the user)
src/main/java/.../Application.java (to bootStrap the application)
src/main/resources/application.yaml (key-value pairs - spring.application.name: simple)
src/main/resources/static/index.html
```
where index.html

```
<!DOCTYPE html>
<html>
<head>
<title>Snowdrop Spring Boot Missions</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
	<div class="jumbotron">
		<h1>Simple Spring Boot template</h1>
		<p>Interested to discover more. Click on the go button ...</p>
		<p>
          <a class="btn btn-lg btn-primary" name="go" role="button">Go &raquo;</a>
        </p>
	</div>
	<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
	<script type="text/javascript"
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script>
	  $("a[name='go']").click(function() {
		window.open('https://github.com/snowdrop?q=-booster');
  	  });
	</script>	
</body>
</html>
```
![screenshot 2017-07-04 10 31 11](https://user-images.githubusercontent.com/463790/27821857-ff1d105e-60a3-11e7-9fcd-a436b7aa4299.png)

 `go` button will open a new tab containing the Spring Boot missions

REMARK:
- We could also based on the module/dependency selected use an associated forge command to add by example for : 
  - jpa: an entity class, hibernate config
  - jax-rs: an endpoint

**Comment by gastaldi** [comment]
This is what the Create flow does. Closing now
