### ISSUE TITLE
Handle memory for Java processes in a container better

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#32]
At the moment our Jenkins Slave image is setting a global env var to set `-Xmx=128m`; this keeps the JVM from overallocating memory as reported available from the host but not to the container.  It would be more efficient to have the JRE manage memory for us respecting container limits.

Blog post explaining some fundamentals:

https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/

In particular, look at property: `-XX:+UseCGroupMemoryLimitForHeap`.  

And be certain the version of the JRE used in the image is up-to-date enough to take advantage of this new flag and feature.

**Comment by omajid** [comment]
Ping. Are there any blockers or issues implementing these changes? Is there anything our team can help with?

cc @grokem

**Comment by gastaldi** [comment]
Out of date. Closing
