### ISSUE TITLE
Support Fabric8 Jenkinsfile Library

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#35]
Reusable pipeline library located at:

  https://github.com/fabric8io/jenkins-pipeline-library

RHT Internal Ref: https://issues.jboss.org/projects/OBST/issues/OBST-275

**Comment by rhoads-zach** [comment]
Linking this issue so doc updates are made based on changes made from this issue:
https://github.com/openshiftio/appdev-documentation/issues/283

**Comment by Ladicek** [comment]
https://github.com/fabric8io/fabric8-team-components/issues/119

**Comment by Ladicek** [comment]
Also for the Swarm booster to build (which includes running the Swarm Arquillian test, and hence starting a _3rd_ Java process in the build container), I had to adjust memory limits: https://github.com/fabric8io/fabric8-pipeline-library/pull/293

**Comment by Ladicek** [comment]
For https://github.com/fabric8io/fabric8-team-components/issues/119, I sent https://github.com/fabric8io/fabric8-team-components/pull/122

**Comment by Ladicek** [comment]
I checked the Health Check boosters and there are no other changes needed (besides those described above).

I also checked the ConfigMap boosters, but none of them work properly on OSIO right now, because they assume a bunch of preparations done in our `Jenkinsfile`s. I think addressing this is currently work in progress.

**Comment by Ladicek** [comment]
I think I didn't mention this here yet, but one additional issue with Swarm boosters on OSIO was [SWARM-1518](https://issues.jboss.org/browse/SWARM-1518). This was already fixed and released, so this will be gone when [SWARM-1538](https://issues.jboss.org/browse/SWARM-1538) is resolved.

**Comment by gastaldi** [comment]
The openshift.io team is working on a Build.Next that will deprecate these files. Closing this issue for now
