### ISSUE TITLE
Show environment-aware and Booster-aware docs in the launcher

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#38]
At the moment we ask the user to choose steps like, "Go continue select the runtime guide" and then present options for Swarm, Vert.x, Boot.  However we know what the user has just launched, so we can surface the correct links or embed directly.  Let's discuss how we get this context properly surfaced.

**Comment by gastaldi** [comment]
Related to https://github.com/openshiftio/appdev-planning/issues/33

**Comment by gastaldi** [comment]
Let's split this into smaller, action-focused issues. Closing
