### ISSUE TITLE
Automated Booster Release / Integration Process

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#44]
Request from the OSIO team.

Allow for automated process by which Boosters, upon release, may be independently tested and integrated into the LOSIO and OSIO systems.

**Comment by rhoads-zach** [comment]
@inoxx03 @tradej @lavernw1 

I'd like to see us add some automation/testing to the docs repo as well. Testing portion is tracked here:
https://github.com/openshiftio/appdev-documentation/issues/297

**Comment by jstrachan** [comment]
this basically means we'd like to maintain our own catalog where we use CI to verify all versions of all boosters work in OSIO before they get into the OSIO catalog.

Then as a new booster is released we can automate a PR against our OSIO catalog's git repo and only if it passes all the OSIO tests does it get to prod OSIO

**Comment by gastaldi** [comment]
> this basically means we'd like to maintain our own catalog where we use CI to verify all versions of all boosters work in OSIO before they get into the OSIO catalog.

Why having your own catalog and not just one that is used by us all? I think this strategy is valid for us too.

**Comment by jstrachan** [comment]
how could we verify 1 version change to 1 booster works in a CI job for our catalog on OSIO with OSIO tests if we just use the 1 git tag that you give us? If you can set all that up for us that'd be great.

If not we can just have our own catalog and we use our CI tests to verify changes to versions of boosters

**Comment by edewit** [comment]
So I think these problems will solve themselves as we will move to a more CI flow. One thing we might need to figure out is how to spring off 2 integration tests ours and yours. We could also try fix all the integration problems you are now having, so there is no need for a separate catalog. BTW we now have a branch of the catalog for you, doesn't that suffice? When we hook up a webhook on all the booster repos and then when tested successfully create a PR on the catalog branch?

**Comment by jstrachan** [comment]
@edewit lets say we're at version 1.0 of all the boosters. Then 2 folks release new versions of 2 boosters. One works on OSIO and one doesn't. So we'd be stuck on the 1.0 versions of all boosters right until both boosters are fixed so we can move to the new version?

I guess I don't yet grok how to use a single version of all boosters in a granular microservice like way. With microservices we can upgrade any version of anything at any time independently. Having 1 global repo with 1 version/tag is gonna be tricky; the catalog then becomes a monolith where we can only make changes when all boosters work on OSIO which seems like it'll just get slower and slower to release and more and more complex to manage as the number of boosters increase and the number of platforms we have to test on increases. 

e.g. already today we need to test for OSIO/fabric8 on OSO free, OSO paid then the various on premise fabric8 platforms (minikube, minishift, kubernetes + OSD).

Using a monolith release of boosters doesn't seem practical to be but if your team can make it all work for OSIO I'd be most grateful! :)

**Comment by edewit** [comment]
@jstrachan well now we do a monolith release of the boosters by tagging them all at the same time, but we could perform all this testing automated on each PR and then when the PR works update the booster catalog automatically to include the latest booster (we could use a hash or another tag). Now that some boosters don't work for you we would keep a branch in the catalog for you and a branch for us. Once we have all boosters working for you as well we can delete this branch. How does that sound?

One thing I'm not sure about is how we do a webhook that notifies us and your integration tests simultaneously, but that sounds like something not so hard.

**Comment by jstrachan** [comment]
I've only ever seen good automated CI / CD work well with fine grained microservices with independent versions/changes; not sure how a monolithic approach is gonna work out in practice - but am very happy for you to try it out

**Comment by edewit** [comment]
right, that is why we'll stop doing that. This ticket it to resolve the issue.
