### ISSUE TITLE
Productized repositories/branches

### ISSUE THREAD

**Issue by kenfinnigan** [fabric8-launcher/launcher-planning#49]
Is it acceptable for productized repositories or branches to be public, given they refer to product versions and would need to include product Maven repositories for building?

If they can't be public, can LOSIO/Forge connect to internal git repositories for cloning?

**Comment by gastaldi** [comment]
Now the catalog requires the full Git URL for the booster code, meaning that it could support other Git servers besides GitHub.

The support for cloning internal repositories will depend if the Openshift cluster where the backend runs can connect to the internal repository, but that's basically an infrastructure issue, not something we need to change in the code.
