### ISSUE TITLE
Deploy booster in an existing OpenShift Project

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#50]
OSO Free clusters (us-east-2 starter for example) has a quota on the possible projects (max 1). When OSIO is setup in your account, that means you can't create another project (namespace) in that OpenShift cluster, so the solution is to deploy suggested by Aslak is to deploy the booster in an existing OpenShift project.

**Comment by gastaldi** [comment]
Chat log: https://chat.openshift.io/developers/pl/5u8khtyjkpgjjgygjyey1pqsuw

**Comment by jstrachan** [comment]
also if you use a pipeline based BuildConfig then by default OSO will create a Jenkins master in that namespace. So creating 2 boosters in 2 different namespaces would result in 2 jenkins master which soon eats up your entire OSO free tier quota.

So the default should be for boosters to reuse the users default project where possible; whether thats the 1 in OSO or the main user namespace in OSIO - to avoid jenkins craziness

**Comment by gastaldi** [comment]
The addon now displays a warning if an existing project is chosen, but the UI allows you to deploy on it. The UI needs to be enhanced to display a list of available projects
