### ISSUE TITLE
Add feature flag to assume ZIP download only option

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#51]
Would skip the deployment type screen and assume "Download as ZIP"

**Comment by quintesse** [comment]
Perhaps just activate this automatically when GitHub/OpenShift auth info is missing?

**Comment by gastaldi** [comment]
And Keycloak info is missing too?

**Comment by gastaldi** [comment]
Is this still needed or is out-of-date because we now do s2i?

**Comment by gastaldi** [comment]
It would be nice to have a real use case scenario. Closing for now, reopen if necessary
