### ISSUE TITLE
Add buildProfileParameter to the launcher

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-planning#55]
The booster catalog yaml config file accepts as parameter a profile:

```
githubRepo: snowdrop/product-spring-boot-circuit-breaker-booster
gitRef: master
buildProfile: whatever
```

but we can't specify a properties to pass to the profile. This is why I would like to propose to add  `buildProfileParameters` where we can express using as convention key1=val1,key2=val2,..... parameters to pass to the profile

Why :  
Spring Boot will rely on a profile definition to pass as parameter the productized version to be used instead of using distinct upstream/downstream git repo to manage the booster content. With such a parameter, we will be able to specify the prod version of the Spring Boot BOM to be used for the launch catalog.

e.g. 

```
<profile>
...
<profile>
<id>product</id>
<properties>
<spring-boot.bom.version>${prod-version}</spring-boot.bom.version>
</properties>

where prod-version key = 2.0.0.redhat-77

and catalog

githubRepo: snowdrop/product-spring-boot-circuit-breaker-booster
gitRef: v7
buildProfile: redhat
buildProfileParameters: 
  - name: prod-version
     value: 2.0.0.redhat-77
```

**Comment by gastaldi** [comment]
@cmoulliard why this parameter needs to be specified in the booster and not directly in the `spring-boot.bom.version` property itself?

**Comment by cmoulliard** [comment]
@gastaldi To avoid that it appears within the upstream project hosted on github

**Comment by gastaldi** [comment]
@cmoulliard thanks for the response, but why would you want to avoid to display that? Wouldn't that information be in the booster-catalog anyway?

**Comment by gastaldi** [comment]
The original intent was that every booster had their own versioning. The problem of putting in the booster-catalog is because you have to change it when a new version comes along too, instead of changing just the `gitRef` for the new supported version.

**Comment by cmoulliard** [comment]
As launch is tagged when it is released, such versions will be part of the version tagged = released and pushed on launch.openshift.io - correct ? When a new launch version will be prepared for a next release where by example we will propose to include the work done for RHOAR Beta2, we will adapt such parameters like you will also do for the gitRef as we have to point to the appropriate boosters which have also been tagged with their corresponding upstream or prod version ...

**Comment by gastaldi** [comment]
@edewit @ALRubinger @quintesse thoughts? I am still not 100% convinced that we should be doing that :)

**Comment by edewit** [comment]
@cmoulliard I don't get it entirely... so instead of having a commit that changes a version number in a pom file you want to have a commit in the booster catalog that changes a version number. But why?

**Comment by cmoulliard** [comment]
To avoid that the PROD version number appears within the upstream project

**Comment by edewit** [comment]
@cmoulliard but all these version numbers will be in the bom as well right? And this version will be a separate branch?

**Comment by gastaldi** [comment]
Out of date, closing
