### ISSUE TITLE
Revisit need for booster.yaml in Booster repositories

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#65]
As it is, it is quite cumbersome to track human-readable version names and keep them in sync with the information that lives in booster catalog. It would simplify the maintenance if we got rid of booster.yaml and put the information that currently lives there in booster catalog

Implementation issues:

 - fabric8-launcher/launcher-booster-catalog-service#22
 - fabric8-launcher/launcher-backend#28

**Comment by quintesse** [comment]
Btw, this change could perhaps also remove the need to retrieve all the boosters from GitHub at startup. It would add an extra step to the Launch process of course: first retrieving the Booster from GitHub before making the necessary changes to it and pushing it again to the user's account. But it would make the backend less complex perhaps and stateless (no need to have anything running, it's just code that gets run at the right time).

**Comment by metacosm** [comment]
Indeed, this would allow Launch to get all the booster metadata from the catalog. I also assume that with one less file to parse, it would also make the launcher simpler. 
Another aspect of things that we might need to consider as well while refactoring that metadata aspect is internationalization of that metadata… Not fun but probably needed at some point. Re-thinking the metatada might be a good point to consider these issues as well! :)

**Comment by heiko-braun** [comment]
I am all for it.

**Comment by ALRubinger** [comment]
+1

**Comment by quintesse** [comment]
Ok, this is done now. All relevant information can be found here:

https://github.com/fabric8-launcher/launcher-booster-catalog/wiki/HOWTO-Create-a-Booster-Catalog-(Generic)
https://github.com/fabric8-launcher/launcher-booster-catalog/wiki/HOWTO-Create-a-Booster-Catalog-(RHOAR)
