### ISSUE TITLE
Allow composition of services in a booster

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#67]
It would be nice if the generator allowed the user to choose the services they would need (in a similar way that start.spring.io does) when generating a project. 

Verify how would that work together with the OpenShift Service Catalog (https://docs.openshift.com/container-platform/3.6/architecture/service_catalog/index.html)

**Comment by rdruss** [comment]
@gastaldi, is this still valid given the new Create Application flow?

**Comment by gastaldi** [comment]
I think the Create application flow fills that purpose. I'll close this issue, thanks :+1:
