### ISSUE TITLE
Decouple adding of a new runtime from launchpad-frontend

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#73]
_From @valdar on November 27, 2017 22:23_

Ideally should be possible to add a new runtime just by modifying https://github.com/fabric8-launch/booster-catalog.

The only needed pieces here are in https://github.com/fabric8-launch/launchpad-frontend/tree/master/src/assets/img/project-select-icons ?

_Copied from original issue: fabric8-launch/launchpad-frontend#214_

**Comment by edewit** [comment]
@valdar are you telling me that this doesn't work cause it should already be like this.

**Comment by valdar** [comment]
It is, the only missing thing is linking an icon to the newly created runtime.
