### ISSUE TITLE
Decouple adding of a new mission from launchpad-frontend

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#74]
_From @valdar on November 27, 2017 22:25_

Ideally should be possible to add a new mission just by modifying https://github.com/fabric8-launch/booster-catalog.

The only needed pieces here are in https://github.com/fabric8-launch/launchpad-frontend/blob/master/src/assets/adoc.index ?

_Copied from original issue: fabric8-launch/launchpad-frontend#215_

**Comment by edewit** [comment]
Same here this should work could you tell me what the issue is?

**Comment by valdar** [comment]
The description of a new mission seems to come from launchpad-frontend projects, so is not possible to just modify the catalog in order to add a new one.

**Comment by gastaldi** [comment]
The new booster catalog already provides this and so the new UX. Closing now.
