### ISSUE TITLE
Migration plan to code-base merging and new repository naming

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#75]
- [x] Rename repositories
- [x] Make sure all vestiges of "launchpad" are removed. 
- [x] Make things work. 
- [x] Merge branches into master. 
- [x] Fix CI/CD 
- [x] Talk with the SD guys with a plan to replace production with our new template

**Comment by quintesse** [comment]
Hey, that's my list ;)
