### ISSUE TITLE
Move openshiftio/booster-parent to fabric8-launcher/launcher-booster-parent

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#79]
Coordinate with runtime teams for ownership, particularly @cescoffier

**Comment by ALRubinger** [comment]
Same with booster-common

**Comment by gastaldi** [comment]
We agreed that it looks weird having an io.openshift groupId in the fabric8-launcher organization 

According to @cescoffier: 
> Let’s say that til summit we keep it, and then we see
