### ISSUE TITLE
openshift-online-free branch should be replaced by additional metadata.

### ISSUE THREAD

**Issue by metacosm** [fabric8-launcher/launcher-planning#81]
As it stands the `openshift-online-free` branch is redundant and a maintenance liability. It would be better if boosters could be marked as available on the free tier as part of their metadata instead of having to maintain a branch to record that information.

**Comment by quintesse** [comment]
A suggestion might be to add a special tag to the .yaml file named `environment:`. If it doesn't exist the booster appears in all environments (`dev`, `staging`, `production`). If it does exist you can give it a list of environments where it should appear. (We could even do something more fancy and allow you to say `environment: -free` meaning that you want it to appear everywhere except in the free version)

**Comment by ALRubinger** [comment]
+1

**Comment by gastaldi** [comment]
Perhaps we could reuse the `label:` feature that was introduced some time ago and never used until now

**Comment by quintesse** [comment]
Ok, this is done now. All relevant information can be found here:

https://github.com/fabric8-launcher/launcher-booster-catalog/wiki/HOWTO-Create-a-Booster-Catalog-(Generic)
https://github.com/fabric8-launcher/launcher-booster-catalog/wiki/HOWTO-Create-a-Booster-Catalog-(RHOAR)
