### ISSUE TITLE
Create Community and Contribution Home: launcher.fabric8.io

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#86]

**Comment by ALRubinger** [comment]
For instance check out design done by the Planner team: 

  https://fabric8-ui.github.io/fabric8-planner/

**Comment by gastaldi** [comment]
That looks cool for a first version.  +1 to reuse that.

**Comment by ALRubinger** [comment]
Also keep in mind the excellent prototyping done by @rhoads-zach

**Comment by gastaldi** [comment]
The SD team has created https://redhat.service-now.com/surl.do?n=RITM0243107 to request transferring the fabric8.io DNS to the RH servers

**Comment by ALRubinger** [comment]
Excellent!

**Comment by gastaldi** [comment]
DNS registered: launcher.fabric8.io 

The SD team is now after the fabric8.io TLS certificates to add the appropriate route

**Comment by gastaldi** [comment]
http://launcher.fabric8.io and http://launcher-preview.fabric8.io are now online. I created https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1997 to enable HTTP/S. 

Closing this issue.
