### ISSUE TITLE
Enable "incremental" flag in s2i builds

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#90]
RHT Only reference: https://issues.jboss.org/browse/OBST-418

@gastaldi, mind looking into this so we may clear it from the product backlog?

**Comment by gastaldi** [comment]
- [ ] Verify if the Vert.x boosters have this flag set in their `.openshiftio/application.yaml` files 
- [ ] Verify if the WildFly Swarm boosters have this flag set in their `.openshiftio/application.yaml` files 
- [ ] Verify if the Spring Boot boosters have this flag set in their `.openshiftio/application.yaml` files
- [ ] Verify if the Node.js boosters have this flag set in their `.openshiftio/application.yaml` files

**Comment by gastaldi** [comment]
Pull requests created. Now we need the runtime owners to merge them, release and then update booster-catalog. /cc @lholmquist @heiko_braun @kenfinnigan

**Comment by lholmquist** [comment]
👀
