### ISSUE TITLE
LAUNCHER_BOOSTER_CATALOG_REPOSITORY can be a git repo on the file system

### ISSUE THREAD

**Issue by lholmquist** [fabric8-launcher/launcher-planning#96]
When developing locally, it would be nice if i could point this env var, LAUNCHER_BOOSTER_CATALOG_REPOSITORY, to my booster catalog repo on my local file system.

This might speed up development a little when someone is making small changes to the catalog they want to see

**Comment by gastaldi** [comment]
As explained by Andrea Tarocchi, you can specify a Git directory in the `LAUNCHER_BOOSTER_CATALOG_REPOSITORY` and that will work.

 Closing this issue now.
