### ISSUE TITLE
Cannot change configured OSO Cluster

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#97]
Once the cluster association has been set, the Web UI hides a link or explanation to change configured clusters.  This is problematic as provisioning into new clusters may change over time.

Quick fix it to put back the link to manually handle this:

https://sso.openshift.io/auth/realms/rh-developers-launch/account/identity

...but a better, more intelligent solution will have cluster association integrated into the WebUI.

**Comment by ia3andy** [comment]
Maybe I am missing something, but regarding the github association, the solution seems to be more on KC side who should have a better error message and maybe a link to fix the problem. It's nearly impossible to guess how to fix the problem by looking at the current error message:
WE'RE SORRY ...
Federated identity returned by github is already linked to another user.

And on our side we don't really know that the account is linked before getting this error.

**Comment by edewit** [comment]
In order to fix this I think it's a good idea to run a instance of [fabric8-auth](https://github.com/fabric8-services/fabric8-auth)

**Comment by gastaldi** [comment]
Should be resolved when using OAuth for the Openshift service (no Keycloak)
