### ISSUE TITLE
Enable pull-request builds and execution of integration tests in CI server

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#98]
We need our CI server to build pull-requests and run the integration tests for our launcher-backend repository

**Comment by ALRubinger** [comment]
Assign to @Ladicek ?

**Comment by gastaldi** [comment]
This is for the launcher-backend repository specifically. @Ladicek I know you're doing it for the Boosters, can we include the launcher-backend too?

**Comment by Ladicek** [comment]
Should be doable.

**Comment by Ladicek** [comment]
@gastaldi I need a couple of things here:

1. What is the repository?
2. How to run the tests? (I assume something like `mvn clean verify`?)
3. Give the `rhoar-bot` GitHub account admin permissions to the repo. (Needs write permissions to be able to set commit status for the PRs, and admin is needed to be able to manage webhooks.)

**Comment by gastaldi** [comment]
1. https://github.com/fabric8-launcher/launcher-backend/
2. `mvn clean integration-test -Pit`. There are instructions on how to set them up here: https://github.com/fabric8-launcher/launcher-backend/#prerequisites-to-run-integration-tests
3. Done: https://github.com/fabric8-launcher/launcher-backend/invitations

**Comment by gastaldi** [comment]
I wish I had. Right now I test using my personal account :)

**Comment by gastaldi** [comment]
If you look at the run.sh file, you'll see the necessary env vars to run the integration tests

**Comment by Ladicek** [comment]
OK, thanks.

**Comment by Ladicek** [comment]
I'm sorry, I should have updated you why I didn't get to setting this up like I agreed to do. I thought it would be a simple Jenkins job with a trivial Maven invocation, but the need to manage all the access tokens moved it from "this is a no-brainer, I'll have it done in 5 minutes" to "ahhh, I'll need to think about this more thoroughly, and I don't have the time for that now". Once again, I apologize.

**Comment by gastaldi** [comment]
No worries. Now we need to talk to KB to get the access tokens available as jenkins secrets and then merge https://github.com/fabric8-launcher/launcher-backend/pull/75
