### ISSUE TITLE
Transient Error: Cannot configure Git triggers

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#99]
![screenshot4](https://user-images.githubusercontent.com/199891/35492608-eabef402-047b-11e8-8b6d-832a39db25af.png)

Check the logs on `developers.redhat.com/launch` for `NoSuchElementException` to get full trace.

**Comment by gastaldi** [comment]
This is the stacktrace in the logs:
```
  | Caused by: java.util.NoSuchElementException: No value present
  | at java.util.Optional.get(Optional.java:135)
  | at io.fabric8.launcher.core.impl.observers.GitHubStepObserver.createWebHooks(GitHubStepObserver.java:128)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
  | at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:313)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:291)
  | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:269)
  | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:302)
  | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:291)
  | at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:80)
  | at io.fabric8.launcher.web.api.MissionControlResource.lambda$upload$0(MissionControlResource.java:98)
```

Is it always reproducible with your user? Can you give more details on how to reproduce this? I just tried with my user and it works great.

**Comment by ALRubinger** [comment]
On Sun, Jan 28, 2018 at 11:02 PM, George Gastaldi <notifications@github.com>
wrote:

> This is the stacktrace in the logs:
>
>   | Caused by: java.util.NoSuchElementException: No value present
>   | at java.util.Optional.get(Optional.java:135)
>   | at io.fabric8.launcher.core.impl.observers.GitHubStepObserver.createWebHooks(GitHubStepObserver.java:128)
>   | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   | at java.lang.reflect.Method.invoke(Method.java:498)
>   | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
>   | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
>   | at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
>   | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:313)
>   | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:291)
>   | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:269)
>   | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:302)
>   | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:291)
>   | at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
>   | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:80)
>   | at io.fabric8.launcher.web.api.MissionControlResource.lambda$upload$0(MissionControlResource.java:98)
>
> Is it always reproducible with your user? Can you give more details on how
> to reproduce this? I just tried with my user and it works great.
>
Nope.  Didn't do anything out of the ordinary to generate this.  Retried
and worked fine.  Transient PITA.  First suspect is timing and asynchrony
in the remote calls.

**Comment by gastaldi** [comment]
I improved the error message. Let's see how that works out. Reopen if the problem persists
